/-
  TrustBoundaries — Documented Assumptions

  All properties that are assumed rather than proved in our Verity models.
  Each assumption is linked to a specific trust boundary and can be checked
  via `--trust-report` when compiling.

  These assumptions are acceptable because:
  1. They rely on well-audited infrastructure (OZ libraries, EVM precompiles)
  2. They represent cross-contract behavior that should be verified separately
  3. They are cryptographic primitives with no known practical attacks
-/
import Verity.Core

/-!
  ## Assumption 1: ERC20 Token Behavior (SafeERC20)

  **What we assume**: OpenZeppelin's SafeERC20 operations (safeTransfer, safeTransferFrom)
  behave correctly — they transfer the exact amount of tokens and revert on failure.

  **Why it's acceptable**: OpenZeppelin contracts are the industry standard, extensively
  audited, and used by thousands of production contracts.

  **How to verify independently**: Audit the OpenZeppelin v5 ERC20 implementation.

  ---
  ## Assumption 2: Keccak256 Hash Function

  **What we assume**: The keccak256 hash function is collision-resistant and behaves
  as specified in the Ethereum Yellow Paper.

  **Why it's acceptable**: keccak256 (SHA-3) has no known practical collisions.

  **How to verify independently**: This is a cryptographic assumption that cannot be
  proven within Lean/Verity without computational soundness proofs.

  ---
  ## Assumption 3: ECDSA Signature Security

  **What we assume**: ECDSA signatures cannot be forged; only the holder of the
  private key can produce a valid signature for a given message.

  **Why it's acceptable**: ECDSA (secp256k1) is the signature scheme used by Ethereum
  itself. A break would compromise the entire network.

  **How to verify independently**: This is a cryptographic assumption.

  ---
  ## Assumption 4: EVM Execution Model

  **What we assume**: The compiled Yul/bytecode executes correctly on the EVM as
  specified. The `solc` compiler from Yul to EVM bytecode is correct.

  **Why it's acceptable**: `solc` is the official Solidity compiler, battle-tested
  across millions of deployments.

  **How to verify independently**: Differential testing between Verity interpreter
  and EVM execution (70,000+ test vectors in Verity's test suite).

  ---
  ## Assumption 5: Cross-Contract Call Correctness

  **What we assume**: When BondingRegistry calls CiphernodeRegistry.addCiphernode(),
  the ciphernode is actually added to the IMT. When SlashingManager calls
  BondingRegistry.slashTicketBalance(), the balance is actually reduced.

  **Why it's acceptable**: Each contract should be verified independently. Cross-contract
  integration correctness can be verified through integration tests.

  **How to verify independently**: Run the existing Hardhat integration test suite:
  ```bash
  pnpm evm:test
  pnpm test:integration
  ```

  ---
  ## Assumption 6: Global Conservation (Whole-Mapping Sums)

  **What we assume**: Per-transition invariants (e.g., "operator X's balance decreased by Y")
  are sufficient to guarantee global conservation (e.g., "sum of all balances = total deposited").

  **Why it's acceptable**: Per-transition correctness combined with the absence of
  other balance-modifying functions implies global conservation by induction.

  **How to verify independently**: This can be proved in a richer proof system (e.g.,
  Coq with mapping iteration) or validated through property-based testing.

  ---
  ## Assumption 7: ZK Proof System Correctness

  **What we assume**: The ZK proofs generated by the BFV pipeline (C0-C7) are sound —
  a valid proof implies the claimed statement is true.

  **Why it's acceptable**: The ZK circuits are independently audited and formally
  verified in the Noir circuit test suite.

  **How to verify independently**: Run `pnpm noir:test` to verify all circuit constraints.

  ---
  ## How to Check Assumptions at Build Time

  ```bash
  # Generate trust report
  lake exe verity-compiler --trust-report artifacts/trust-report.json

  # Deny specific assumption categories
  lake exe verity-compiler \
    --deny-axiomatized-primitives \
    --deny-low-level-mechanics \
    --trust-report artifacts/trust-report.json
  ```
-/
