#!/usr/bin/env bash
# r170 - C1 eek + sk solo legs (last non-zero C1 flat cell).
# r159 RAN e_sm_lifted solo = 127,023 g of the C1 flat 203,506 g; the r157 flat
# remainder = (eek 5-bit + sk 1-bit) = 76,483 g, RAN-by-subtraction only.
# This round carves those two cells out directly; same solo-NOP harness as r159.
set -u
export PATH="$HOME/.local/bin:$HOME/.nargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
R2SK=${R2SK:-/tmp/r170}
OUT=${OUT:-/home/dev/interfold-research/interfold/poc/r170}
mkdir -p "$OUT"
CFG=${CFG:-$OUT/log.r170}
log(){ echo "[$(date -u +%FT%TZ)] $*" | tee -a "$CFG"; }

if [ -d $R2SK ]; then
  HEAD_NOW=$(git -C $R2SK rev-parse HEAD)
  if [ "$HEAD_NOW" = "a3bf52007228b59f1580d96c24ad236af70f4ecf" ]; then
    log "WORKTREE-EXISTING-REUSE @ $HEAD_NOW"
  else
    log "WORKTREE-EXISTS-WRONG-SHA $HEAD_NOW"; exit 96
  fi
else
  git worktree add --detach $R2SK a3bf52007228b59f1580d96c24ad236af70f4ecf >> $CFG 2>&1 || { log WT_FAIL; exit 96; }
fi
cd $R2SK || { log ERR; exit 96; }
HEAD_NOW=$(git rev-parse HEAD)
echo "$HEAD_NOW" | grep -q '^a3bf52007' || { log BASE-NOT-LOCKED $HEAD_NOW; exit 97; }
log "HEAD=$HEAD_NOW"

[ "$(awk '/^MemAvailable:/{print $2}' /proc/meminfo)" -ge 12000000 ] || { log LOW-MEM; exit 96; }

DEF=$R2SK/circuits/lib/src/configs/default/mod.nr
PK=$R2SK/circuits/lib/src/core/threshold/pk_generation.nr
PRE_DEF=7f07de82407c9601dd737044af69a068238dd9ff175f51c4d64d8e00980aa207
# PRE_PK pinned at script start (disk-truth; not from memory)
PRE_PK=$(sha256sum "$PK" | cut -d' ' -f1)
[ "$(sha256sum "$DEF" | cut -d' ' -f1)" = "$PRE_DEF" ] || { log PRE_DEF_MISMATCH; exit 99; }
log "PRE_PK=$PRE_PK"
cp -f "$DEF" "$OUT/zz_default_mod.nr.bak"
cp -f "$PK"  "$OUT/zz_pk_generation.nr.bak"
restore() {
  cp -f "$OUT/zz_default_mod.nr.bak" "$DEF"
  cp -f "$OUT/zz_pk_generation.nr.bak" "$PK"
  if [ "$(sha256sum "$DEF" | cut -d' ' -f1)" = "$PRE_DEF" ] && \
     [ "$(sha256sum "$PK"  | cut -d' ' -f1)" = "$PRE_PK" ]; then
    log "RESTORED rc=0"; return 0
  fi
  log "RESTORED rc=1"; return 1
}
trap 'log INTERRUPT-RESTORE; restore' TERM INT

flip_def() {
  python3 - "$DEF" <<'PY'
import sys
p=sys.argv[1]; a=open(p,encoding='utf-8').read()
s=a.replace('Auto-generated by build-circuits.ts for preset: insecure-512','Auto-generated by build-circuits.ts for preset: secure-8192')
s=s.replace('pub use super::insecure::dkg;','pub use super::secure::dkg;')
s=s.replace('pub use super::insecure::threshold;','pub use super::secure::threshold;')
assert s!=a, 'preset flip miss'
open(p,'w').write(s); print('FLIP_OK')
PY
}

compile_one() {
  local tag=$1
  local art=$R2SK/circuits/bin/threshold/target/pk_generation.json
  local s e rc
  cd "$R2SK/circuits/bin/threshold" || { log ${tag}_CD_FAIL; return 96; }
  rm -f "$art"
  s=$(date +%s)
  taskset -c 0-3 /usr/bin/time -v nargo compile --force > "$OUT/${tag}_stdout.log" 2> "$OUT/${tag}_timev.log"
  rc=$?
  e=$(date +%s)
  echo "$((e-s))s" > "$OUT/${tag}_wall.raw"
  log "$tag rc=$rc wall=$((e-s))s"
  cd "$R2SK" || return 99
  [ $rc -ne 0 ] && return $rc
  [ -s "$art" ] || return 100
  cp -f "$art" "$OUT/${tag}_fresh.json"
  bb gates -b "$OUT/${tag}_fresh.json" -t noir-recursive-no-zk > "$OUT/${tag}_gates.json" 2> "$OUT/${tag}_gates_err.log"
  return 0
}

caption() {
  local tag=$1
  python3 - "$OUT" "$tag" <<'PY'
import json,sys,datetime
out,tag=sys.argv[1],sys.argv[2]
try:
  d=json.load(open(out+'/'+tag+'_gates.json'))
  g=sum(f.get('circuit_size',0) for f in d.get('functions',[]))
  ac=sum(f.get('acir_opcodes',0) for f in d.get('functions',[]))
  wall=0.0; peak=0
  for l in open(out+'/'+tag+'_timev.log',errors='replace'):
    if 'Elapsed (wall clock)' in l:
      t=l.split(':',1)[1].strip().rsplit(' ',1)[-1]
      try:
        p=t.split(':'); wall=float(p[0])*60+float(p[1])
      except Exception: pass
    if 'Maximum resident set size' in l:
      peak=int(l.split()[-1])
  line=f"ROUND=r170 LEG={tag} BASE=a3bf52007 DATE={datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')} GATES={g} ACIR={ac} WALL={wall:.1f}s PEAK_KB={peak}"
except Exception as e:
  line=f'ROUND=r170 LEG={tag} PARSE_ERR={e}'
open(out+'/'+tag+'.r170','w').write(line+"\n")
print(line)
PY
}

# ---- LEG A1: unblunt re-anchor (entirely outside any change) ----
flip_def || { log FLIP_FAIL_A1; restore; echo R170_STATUS=A1_FLIPFAIL | tee -a $CFG; exit 97; }
compile_one r170A1_live || { log A1_FAIL; restore; echo R170_STATUS=A1_FAIL | tee -a $CFG; exit 101; }
caption r170A1_live || { log A1_PARSE_FAIL; restore; echo R170_STATUS=A1_PARSE_FAIL | tee -a $CFG; exit 102; }
log "LEG_A1_DONE"

# ---- LEG E: eek solo NOP ----
[ "$(sha256sum "$PK" | cut -d' ' -f1)" = "$PRE_PK" ] || { log PK_STATE_DRIFT_E; restore; echo R170_STATUS=PK_STATE_DRIFT_E | tee -a $CFG; exit 103; }
python3 - "$PK" <<'PY'
import sys
p=sys.argv[1]; a=open(p,encoding='utf-8').read()
lines=a.split('\n')
n=0
for i,l in enumerate(lines):
    s=l.strip()
    if s.startswith('//R170_EEK_'):
        continue
    if s.startswith('self.eek') and 'range_check' in s:
        lines[i]='//R170_EEK_' + l
        n+=1
assert n>=1 and n<=2, f'expected eek call site 1..2 occurrences, saw {n}'
open(p,'w').write('\n'.join(lines))
print(f'EEK_KITTED n={n}')
PY
[ $? -eq 0 ] || { log SPFAIL_EEK; restore; echo R170_STATUS=SPFAIL_EEK | tee -a $CFG; exit 104; }
[ "$(sha256sum "$PK" | cut -d' ' -f1)" != "$PRE_PK" ] || { log EEK_NOCHANGE; restore; echo R170_STATUS=EEK_NOCHANGE | tee -a $CFG; exit 105; }
compile_one r170E_eek_solo || { log E_FAIL; restore; echo R170_STATUS=E_FAIL | tee -a $CFG; exit 106; }
caption r170E_eek_solo || { log E_PARSE_FAIL; restore; echo R170_STATUS=E_PARSE_FAIL | tee -a $CFG; exit 107; }
cp -f "$OUT/zz_eek_shifted.nr.bak" /dev/null 2>/dev/null || true
restore || { log E_RESTORE_FAIL; echo R170_STATUS=E_RESTORE_FAIL | tee -a $CFG; exit 108; }
log "LEG_E_DONE"

# ---- LEG S: sk solo NOP ----
# NOTE (corrections-first): DEF must be flipped to secure-8192 BEFORE compiling
# Leg S (Leg E's restore() put DEF back to insecure-512). Without this flip Leg S
# compiles at insecure-512 and returns a tiny mangled circuit. Added this round
# after the first Sk leg (wall 3 s) proved it. See poc/r170/log.r170.
flip_def || { log FLIP_FAIL_S; restore; echo R170_STATUS=S_FLIPFAIL | tee -a $CFG; exit 109; }
python3 - "$PK" <<'PY'
import sys
p=sys.argv[1]; a=open(p,encoding='utf-8').read()
lines=a.split('\n')
n=0
for i,l in enumerate(lines):
    s=l.strip()
    if s.startswith('//R170_SK_'):
        continue
    if s.startswith('self.sk.') and 'range_check' in s:
        lines[i]='//R170_SK_'+l
        n+=1
assert 1<=n<=2, f'expected sk call site 1..2 occurrences, saw {n}'
open(p,'w').write('\n'.join(lines))
print(f'SK_KITTED n={n}')
PY
[ $? -eq 0 ] || { log SPFAIL_SK; restore; echo R170_STATUS=SPFAIL_SK | tee -a $CFG; exit 114; }
[ "$(sha256sum "$PK" | cut -d' ' -f1)" != "$PRE_PK" ] || { log SK_NOCHANGE; restore; echo R170_STATUS=SK_NOCHANGE | tee -a $CFG; exit 110; }
compile_one r170S_sk_solo || { log S_FAIL; restore; echo R170_STATUS=S_FAIL | tee -a $CFG; exit 111; }
caption r170S_sk_solo || { log S_PARSE_FAIL; restore; echo R170_STATUS=S_PARSE_FAIL | tee -a $CFG; exit 112; }
restore || { log S_RESTORE_FAIL; echo R170_STATUS=S_RESTORE_FAIL | tee -a $CFG; exit 113; }
log "LEG_S_DONE"

# ---- delta + identity cross-check ----
python3 - "$OUT" <<'PY'
import json,sys
out=sys.argv[1]
def load(tag):
    d=json.load(open(out+'/'+tag+'_gates.json'))
    g=sum(f.get('circuit_size',0) for f in d.get('functions',[]))
    ac=sum(f.get('acir_opcodes',0) for f in d.get('functions',[]))
    return g,ac
A1,A1a=load('r170A1_live'); E,Ea=load('r170E_eek_solo'); S,Sa=load('r170S_sk_solo')
R159_FLAT_REMAINDER=76483  # r157 flat 203,506 - r159 e_sm_lifted 127,023
LINES=['ROUND=r170  (C1 eek + sk solo legs; closes the r159 remainder 76,483 g to direct RAN cells)']
LINES.append(f'A1 = {A1} g   ACIR={A1a}   (expect 1,634,722 r157/r159 golden delta 0)')
LINES.append(f'E  = {E} g   ACIR={Ea}')
LINES.append(f'Sk = {S} g   ACIR={Sa}')
if A1==1634722:
    LINES.append('A1 r159 text-SHA256 pad: EXACT (applies)')
ee=A1-E; ss=A1-S
LINES.append(f'eek_solo=A1-E={ee} g   sk_solo=A1-S={ss} g')
LINES.append(f'both=ee+ss={ee+ss} g   vs r159 remainder={R159_FLAT_REMAINDER} g   delta={ee+ss-R159_FLAT_REMAINDER}')
LINES.append(f'eek/sk ratio={ee/ss if ss else float("inf"):.4f}')
open(out+'/r170_delta.r170','w').write('\n'.join(LINES)+'\n')
print('\n'.join(LINES))
PY
echo "R170_STATUS=OK" | tee -a "$CFG"
exit 0