#!/usr/bin/env bash
# r152f - C0 (dkg/pk) re-anchor at NEW upstream base c98b0d1ca (#1999).
# Close-out of the per-leaf re-anchor table opened by #1999.
# Working branch i5/dkg-research @ 578b07b65 (r152d tip); evidence base c98b0d1ca
# (rebase onto origin/main RED-BLOCKED at commit 13/93 share_encryption.nr -- do NOT force;
#  this tick's origin/main b331a5d9c = 4 more NET-ONLY commits since c98b0d1ca,
#  circuits/ diff c98b0d1ca..b331a5d9c = 0 lines -> base stays locked at c98b0d1ca).
# Detached worktree /tmp/r151b @ c98b0d1ca.
# 1 leg, measurement-only (NEVER shipped):
#   A0 : unblunt C0 re-anchor (dkg/pk, exec = Pk::execute -> compute_dkg_pk_commitment)
#        Old-base golden (r39/r75/r100 era): 287,727 g / ACIR 14,568.
# Premise pre-verified at SOURCE this round (see LOG):
#   - #1999 touched neither circuits/bin/dkg/pk/ nor circuits/lib/src/core/dkg/pk.nr
#   - pk.execute() -> compute_dkg_pk_commitment (commitments.nr:190) has 0 range_check_*
#     in its direct cone (compliant with the r99/r100/r145/r150 class)
# nargo beta-26 writes the artifact to PACKAGE-ROOT target: circuits/bin/dkg/target/pk.json
set -u
export PATH="$HOME/.local/bin:$HOME/.nargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
R=/tmp/r151b
OUT=/home/dev/interfold-research/interfold/poc/r152f
TGT=$R/circuits/bin/dkg/target
CIR=pk

log(){ echo "[$(date -u +%FT%TZ)] $*" | tee -a /tmp/r152f.log; }

cd "$R" || { log ERR_CD; exit 96; }
mkdir -p "$OUT"
log "HEAD=$(git rev-parse HEAD)"
git rev-parse HEAD | grep -qE '^c98b0d1ca' || { log BASE-NOT-LOCKED; exit 97; }
[ "$(git status --porcelain)" = "" ] || { log DIRTY; git status --porcelain | head -5; exit 98; }
AVAIL_KB=$(awk '/^MemAvailable:/{print $2}' /proc/meminfo)
[ "$AVAIL_KB" -ge 20000000 ] || { log "NOGO_PRE_MEM=$AVAIL_KB"; exit 96; }
log "PRE_MEM_AVAIL_KB=$AVAIL_KB"

DEF=$R/circuits/lib/src/configs/default/mod.nr
ACT=$R/circuits/lib/src/configs/committee/active.nr
PKNR=$R/circuits/lib/src/core/dkg/pk.nr
COM=$R/circuits/lib/src/math/commitments.nr

PIN_DEF=$(sha256sum "$DEF" | cut -d' ' -f1)
PIN_ACT=$(sha256sum "$ACT" | cut -d' ' -f1)
PIN_PK=$(sha256sum "$PKNR"  | cut -d' ' -f1)
PIN_COM=$(sha256sum "$COM"  | cut -d' ' -f1)
PIN_JSON=$(sha256sum "$TGT/$CIR.json" 2>/dev/null | cut -d' ' -f1 || echo none)
log "PRE_DEF=$PIN_DEF ACT=$PIN_ACT PKNR=$PIN_PK COM=$PIN_COM PRE_JSON=$PIN_JSON"

_R152F_RESTORED=0

cp -f "$DEF"  "$OUT/zz_default_mod.nr"
cp -f "$ACT"  "$OUT/zz_active.nr"
[ "$PIN_JSON" != "none" ] && cp -f "$TGT/$CIR.json" "$OUT/pre_pk.json"

restore(){
  [ "$_R152F_RESTORED" = "1" ] && return
  log TRAP-RESTORE
  cp -f "$OUT/zz_default_mod.nr" "$DEF"
  cp -f "$OUT/zz_active.nr"      "$ACT"
  if [ "$PIN_JSON" != "none" ]; then
    cp -f "$OUT/pre_pk.json" "$TGT/$CIR.json"
  else
    rm -f "$TGT/$CIR.json"
  fi
  if diff -q "$OUT/zz_default_mod.nr" "$DEF" >/dev/null 2>&1 && \
     diff -q "$OUT/zz_active.nr"      "$ACT" >/dev/null 2>&1; then
    log RESTORED_OK
  else
    log RESTORE_FAIL
  fi
  _R152F_RESTORED=1
}
trap restore TERM INT

flip_preset(){
  python3 - "$DEF" <<'PY'
import sys
p=sys.argv[1]; a=open(p).read()
s=a.replace('Auto-generated by build-circuits.ts for preset: insecure-512',
            'Auto-generated by build-circuits.ts for preset: secure-8192')
s=s.replace('pub use super::insecure::dkg;','pub use super::secure::dkg;')
s=s.replace('pub use super::insecure::threshold;','pub use super::secure::threshold;')
assert s!=a, 'preset flip miss'
open(p,'w').write(s); print('FLIP_OK')
PY
}

### ====== LEG A0: C0 unblunt re-anchor ======
flip_preset || { log FLIP_FAIL A0; restore; exit 97; }
rm -f "$TGT/$CIR.json"
cd "$R/circuits/bin/dkg/pk" || { log A0_CDFAIL; restore; exit 97; }
( while :; do
    awk '/^MemTotal:/{t=$2} /^MemAvailable:/{a=$2} END{printf "%d\n",(t-a)/1024}' /proc/meminfo
    sleep 8
  done ) > "$OUT/A0_ram_trace.log" 2>/dev/null &
SAMPID=$!
E0=$(date +%s)
taskset -c 0-3 /usr/bin/time -p nargo compile --force \
  > "$OUT/A0_stdout.log" 2> "$OUT/A0_timev.log"
RC=$?
E1=$(date +%s)
kill "$SAMPID" 2>/dev/null; wait "$SAMPID" 2>/dev/null
cd "$R" || exit 96
WALL=$((E1-E0))
log "A0 RC=$RC WALL=${WALL}s"
if [ $RC -ne 0 ]; then log A0_COMPILE_FAIL; restore; exit 98; fi
[ -s "$TGT/$CIR.json" ] || { log A0_NO_ARTIFACT; restore; exit 100; }
cp -f "$TGT/$CIR.json" "$OUT/A0_fresh.json"
sha256sum "$OUT/A0_fresh.json" | cut -d' ' -f1 > "$OUT/A0_fresh_sha.txt"
bb gates -b "$OUT/A0_fresh.json" -t noir-recursive-no-zk \
  > "$OUT/A0_gates.json" 2> "$OUT/A0_gates_err.log"
python3 - "$OUT" <<'PY'
import json,sys
out=sys.argv[1]
d=json.load(open(out+'/A0_gates.json')); fns=d.get('functions',[])
g=sum(f.get('circuit_size',0) for f in fns)
ac=sum(f.get('acir_opcodes',0) for f in fns)
peak=0; wall=0.0
for l in open(out+'/A0_timev.log', errors='replace'):
    if 'Maximum resident set size' in l: peak=int(l.split()[-1])
    if 'Elapsed (wall clock)' in l: wall=float(l.split()[-1])
with open(out+'/A0.r152f','w') as fh:
    fh.write(f'ROUND=r152f LEG=A0 CIR=dkg/pk BASE=c98b0d1ca GATES={g} ACIR={ac} WALL={wall:.2f}s PEAK_KB={peak}\n')
print(open(out+'/A0.r152f').read())
PY

restore
### TREE-PIN CHECK ###
PORC=$(git status --porcelain | wc -l)
M_DEF=$(sha256sum "$DEF"  | cut -d' ' -f1)
M_ACT=$(sha256sum "$ACT"  | cut -d' ' -f1)
M_PK=$(sha256sum "$PKNR" | cut -d' ' -f1)
M_COM=$(sha256sum "$COM" | cut -d' ' -f1)
M_JSON=$(sha256sum "$TGT/$CIR.json" 2>/dev/null | cut -d' ' -f1 || echo none)
{
  echo PORC_AFTER=$PORC
  echo DEF_SHA=$M_DEF ACT_SHA=$M_ACT PKNR_SHA=$M_PK COM_SHA=$M_COM
  echo PRE_JSON=$PIN_JSON POST_JSON=$M_JSON
  echo PRESERVED_CONSERVE=$([ "$PIN_JSON" = "$M_JSON" ] || { [ "$PIN_JSON" = "none" ] && [ "$M_JSON" = "none" ]; } && echo ALL_OK || echo DRIFT)
  echo PRESERVED_CONFIG=$([ "$PIN_DEF" = "$M_DEF" ] && [ "$PIN_ACT" = "$M_ACT" ] && [ "$PIN_PK" = "$M_PK" ] && [ "$PIN_COM" = "$M_COM" ] && echo BYTE_EXACT || echo DRIFT)
} > "$OUT/restore_check.txt"
cat "$OUT/restore_check.txt" | while read -r l; do log "$l"; done
log "LEG_END A0=$RC"
exit 0