#!/usr/bin/env bash
# r160 - C3 flat deep-slice @ FOLD tip 733eb45ae (post-#1996 + folds).
#   M  message.range_check_standard::<BIT_MSG> solo NOP on unblunt basis (u/e0/e1 + limb loop stay).
# r156 goldens are carried (C3 locus blob a38431229 byte-identical 7e999546e -> 733eb45ae, RAN blob cmp).
# Worktree: /tmp/r160 @ 733eb45ae (detached). Vessel: in-session foreground + /usr/bin/time -v + taskset -c 0-3.
set -u
export PATH="$HOME/.local/bin:$HOME/.nargo/bin:/usr/local/bin:$PATH"
cd /tmp/r160 || { echo "[ERR] cd worktree"; exit 96; }
OUT=/home/dev/interfold-research/interfold/poc/r160
mkdir -p "$OUT"
DEF=/tmp/r160/circuits/lib/src/configs/default/mod.nr
SE=/tmp/r160/circuits/lib/src/core/dkg/share_encryption.nr
DS=/tmp/r160/circuits/bin/dkg
ART=$DS/target/share_encryption.json
PRE_DEF=7f07de82407c9601dd737044af69a068238dd9ff175f51c4d64d8e00980aa207   # content sha on-disk (blob 76bfde23 git-hash)
PRE_SE=308c8c5dd1f7b00a6650bfafd3c5336511964463a64591c7063e5e258f08756e
log(){ echo "[$(date -u +%FT%TZ)] $*"; }
echo "=== r160 worktree @ $(git -C /tmp/r160 rev-parse HEAD) ===" | tee -a "$OUT/log.r160"
log "PRE_DEF_SHA=$(sha256sum "$DEF" | cut -d' ' -f1)"
log "PRE_SE_SHA =$(sha256sum "$SE" | cut -d' ' -f1)"
if [ "$(sha256sum "$DEF" | cut -d' ' -f1)" != "$PRE_DEF" ] || [ "$(sha256sum "$SE" | cut -d' ' -f1)" != "$PRE_SE" ]; then
  log "PRE-SHA MISMATCH - aborting"; exit 97
fi
cp -f "$DEF" "$OUT/zz_default_mod.nr.bak"
cp -f "$SE"  "$OUT/zz_share_encryption.nr.bak"
restore(){
cp -f "$OUT/zz_default_mod.nr.bak" "$DEF"
cp -f "$OUT/zz_share_encryption.nr.bak" "$SE"
if [ "$(sha256sum "$DEF" | cut -d' ' -f1)" = "$PRE_DEF" ] && [ "$(sha256sum "$SE" | cut -d' ' -f1)" = "$PRE_SE" ]; then
  log "RESTORED rc=0"; return 0
fi
log "RESTORED rc=1 (sha mismatch!)"; return 1
}
trap 'log INTERRUPT-RESTORE; restore' TERM INT

flip_def(){
python3 - "$DEF" <<'PY'
import sys
p=sys.argv[1]; a=open(p).read()
s=a.replace('Auto-generated by build-circuits.ts for preset: insecure-512','Auto-generated by build-circuits.ts for preset: secure-8192')
s=s.replace('pub use super::insecure::dkg;','pub use super::secure::dkg;')
assert s!=a, "preset flip miss"
open(p,'w').write(s); print("FLIP_OK")
PY
}

compile_one(){
  local tag=$1
  cd "$DS" || return 96
  rm -f "$ART"
  local s e
  s=$(date +%s)
  taskset -c 0-3 /usr/bin/time -v nargo compile --force > "$OUT/${tag}_stdout.log" 2> "$OUT/${tag}_timev.log"
  local rc=$?
  e=$(date +%s)
  echo "$((e-s))s" > "$OUT/${tag}_wall.raw"
  log "$tag rc=$rc wall=$((e-s))s"
  cd /tmp/r160 || return 99
  [ $rc -ne 0 ] && return $rc
  [ -s "$ART" ] || return 100
  cp -f "$ART" "$OUT/${tag}_fresh.json"
  bb gates -b "$OUT/${tag}_fresh.json" -t noir-recursive-no-zk > "$OUT/${tag}_gates.json" 2> "$OUT/${tag}_gates_err.log"
  return 0
}

caption(){
python3 - "$OUT" "$1" <<'PY'
import json,sys,datetime
out,tag=sys.argv[1:3]
d=json.load(open(out+"/"+tag+"_gates.json"))
fns=d.get("functions",[]); g=sum(f.get("circuit_size",0) for f in fns); ac=sum(f.get("acir_opcodes",0) for f in fns)
wall=0.0; peak=0
for l in open(out+"/"+tag+"_timev.log",errors="replace"):
    if "Elapsed (wall clock)" in l:
        t=l.split(":",1)[1].strip().rsplit(" ",1)[-1]
        try: p=t.split(":"); wall=float(p[0])*60+float(p[1])
        except Exception: pass
    if "Maximum resident set size" in l:
        peak=int(l.split()[-1])
line="ROUND=r160 LEG=%s BASE=733eb45ae DATE=%s GATES=%d ACIR=%d WALL=%.1fs PEAK_KB=%d"%(
  tag, datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ'), g, ac, wall, peak)
open(out+"/"+tag+".r160","w").write(line+"\n")
print(line)
PY
}

# ============ FLIP + LEG M: message solo NOP on unblunt ============
flip_def || { log FLIP_FAIL; exit 97; }
log FLIPPED
python3 - "$SE" <<'PY'
import sys
p=sys.argv[1]; s=open(p).read()
old='        self.message.range_check_standard::<BIT_MSG>(self.configs.msg_bound);\n'
n=s.count(old); assert n==1, "expected exactly 1 message range check call-site; got %d" % n
new='        // R160-SHADOW-NOP-MSG: self.message.range_check_standard::<BIT_MSG>(self.configs.msg_bound);\n'
s2=s.replace(old,new)
assert s2.count('R160-SHADOW-NOP-MSG')==1
# u / e0 / e1 flat calls must still be live
assert s2.count('self.u.range_check_2bounds')==1
assert s2.count('self.e0.range_check_2bounds')==1
assert s2.count('self.e1.range_check_2bounds')==1
# 4 limb-loop calls must still be live
assert s2.count('self.pk0is[i].range_check_2bounds')==1
assert s2.count('self.pk1is[i].range_check_2bounds')==1
assert s2.count('self.ct0is[i].range_check_2bounds')==1
assert s2.count('self.ct1is[i].range_check_2bounds')==1
assert s2.count('{')==s.count('{') and s2.count('}')==s.count('}'), "brace balance broken"
open(p,'w').write(s2); print("NOP_M_OK")
PY
log "LEG M SPLICE APPLIED"
MV0_KB=$(awk '/^MemAvailable:/{print $2}' /proc/meminfo)
log "MEM_AVAIL_KB_BEFORE_M=$MV0_KB"
compile_one r160M_msg_solo; R_M=$?
if [ $R_M -ne 0 ]; then log "M compile rc=$R_M"; restore; echo "R160_STATUS=M_FAIL rc=$R_M" | tee -a "$OUT/log.r160"; exit 101; fi
caption r160M_msg_solo || { log M_PARSE_FAIL; restore; exit 102; }
log "LEG M DONE rc=$R_M"
MV1_KB=$(awk '/^MemAvailable:/{print $2}' /proc/meminfo)
log "MEM_AVAIL_KB_AFTER=$MV1_KB (was $MV0_KB; net change=$((MV1_KB-MV0_KB)) kB)"
restore; R_RESTORE=$?
log "RESTORE rc=$R_RESTORE after leg M"

# ============ DELTAS (use r156 goldens for A/B/C since blob-frozen) ============
python3 - "$OUT" <<'PY'
import json,sys
def load(t):
  d=json.load(open(sys.argv[1]+"/"+t+"_gates.json"))
  return sum(f.get("circuit_size",0) for f in d.get("functions",[]))
M=load("r160M_msg_solo")
# r156 fold-tip RAN (digit-anchored in poc/r156/delta_auth.r156 + blob-identity 7e999546e -> 733eb45ae):
A1=2124549  # C3A_live
B =1395432  # C3B_full (check_range_bounds fully NOP)
C =1567484  # C3C_limb (per-limb loop only NOP; 4 flat polys + quotient stay)
flat = C - B                        # 172,052 = u + e0 + e1 + message  (all flat polys + flat message)
msg_solo = A1 - M                   # RAN: cost of the message range check itself
rem_flat = flat - msg_solo          # u(1-bit) + e0(5-bit) + e1(5-bit)  -- RAN by subtraction
txt=f"""r160 C3 message solo @ FOLD tip 733eb45ae
  RAN this round:
    M  message solo NOP (u/e0/e1 flat + 4 limb-steps stay) = {M} g
  r156 fold-tip RAN (digit-carry, C3 locus blob a38431229 byte-frozen 7e999546e -> 733eb45ae):
    A1 unblunt          = {A1} g
    B  check_range_bounds full NOP = {B} g
    C  per-limb only NOP          = {C} g
  Delta  RAN:
    message solo cost        = {msg_solo} g = {msg_solo/A1*100:.2f}% of leaf = {msg_solo/(C-B)*100:.2f}% of C3 flat
    flat remaining (u+e0+e1) = {rem_flat} g = {rem_flat/A1*100:.2f}% of leaf = {rem_flat/(C-B)*100:.2f}% of flat
    identity                  = {msg_solo} + {rem_flat} = {msg_solo+rem_flat}  vs r156 flat {C-B}  delta {(msg_solo+rem_flat)-(C-B):+d}
  Reclassified C3 split (family = per-limb + flat; flat = message + u+e0+e1):
    per-limb = {A1-C} g  (r156, byte-frozen)
    message  = {msg_solo} g  (this round, RAN)
    u+e0+e1  = {rem_flat} g  (this round, RAN by subtraction from r156 flat)
    identity per-limb + message + u/e0/e1 = {A1-C} + {msg_solo} + {rem_flat} = {A1-C+msg_solo+rem_flat}
              vs r156-family {A1-B}: delta {(A1-C+msg_solo+rem_flat)-(A1-B):+d}
"""
open(sys.argv[1]+"/r160_delta.r160","w").write(txt)
print(txt)
PY

# ============ STALE-ARTIFACT SENTINEL (pre-commit safety) ============
PORC_NONUNTRACKED=$(git -C /tmp/r160 status --porcelain | grep -v '^??' | wc -l)
log "PORC_NONUNTRACKED=$PORC_NONUNTRACKED"
[ "$PORC_NONUNTRACKED" -eq 0 ] || { log "LEG M left modified files"; exit 107; }
echo "R160_STATUS=OK" | tee -a "$OUT/log.r160"
exit 0