#!/usr/bin/env bash
# r156 - C3 family re-anchor + per-limb slice at FOLD base (HEAD 7e999546e, post-#1996).
# Legs (per plan.md): C3A_live (unblunt), C3B_full (check_range_bounds NOP),
# C3C_limb (per-limb slice NOP: 4 loop calls die, 4 flat + quotient stay).
# Method = r152b/r147 shadow-NOP. Artifact path = workspace target dir (r152b fix).
set -u
export PATH="$HOME/.local/bin:$HOME/.nargo/bin:/usr/local/bin:$PATH"
R=/tmp/r156
OUT=/home/dev/interfold-research/interfold/poc/r156
WTBIN=$R/circuits/bin/dkg
DS=$R/circuits/bin/dkg/target
DEF=$R/circuits/lib/src/configs/default/mod.nr
SE=$R/circuits/lib/src/core/dkg/share_encryption.nr
mlog(){ echo "[$(date -u +%FT%TZ)] $*" >&2; }
cd "$R" || { mlog ERR; exit 96; }
sha(){ sha256sum "$1" | cut -d' ' -f1; }
PRE_DEF=$(sha "$DEF"); PRE_SE=$(sha "$SE")
mlog "PRE_DEF=$PRE_DEF PRE_SE=$PRE_SE"
cp -f "$DEF" "$OUT/pre_default_mod.nr.bak"
cp -f "$SE"  "$OUT/pre_share_encryption.nr.bak"
rest(){
  cp -f "$OUT/pre_default_mod.nr.bak" "$DEF"
  cp -f "$OUT/pre_share_encryption.nr.bak" "$SE"
  if [ "$(sha "$DEF")" = "$(sha "$OUT/pre_default_mod.nr.bak")" ] && [ "$(sha "$SE")" = "$(sha "$OUT/pre_share_encryption.nr.bak")" ]; then
    mlog "RESTORED rc=0"; return 0
  fi
  mlog "RESTORED rc=1 (sha mismatch!)"; return 1;
}
trap 'mlog INTERRUPT-RESTORE; rest' TERM INT
flip(){
python3 - "$DEF" <<'PY'
import sys
p=sys.argv[1]; a=open(p).read()
s=a.replace('Auto-generated by build-circuits.ts for preset: insecure-512','Auto-generated by build-circuits.ts for preset: secure-8192')
s=s.replace('pub use super::insecure::dkg;','pub use super::secure::dkg;')
assert s!=a, "preset flip miss"
open(p,'w').write(s)
print("FLIP_OK")
PY
}
compile_one(){ # $1 TAG
  local tag=$1 rc
  if ! grep -q 'secure-8192' "$DEF"; then mlog "$tag NO-FLIP"; return 80; fi
  cd "$WTBIN" || return 96
  rm -f "$DS"/share_encryption.json
  local s e
  s=$(date +%s)
  /usr/bin/time -v nargo compile --force > "$OUT/${tag}_stdout.log" 2> "$OUT/${tag}_timev.log" &
  NC_PID=$!
  ( sleep 2; true ) &
  wait "$NC_PID"; rc=$?
  e=$(date +%s)
  echo "$((e-s))" > "$OUT/${tag}_wall.raw"
  mlog "$tag rc=$rc wall=$((e-s))s"
  cd "$R" || return 99
  [ $rc -ne 0 ] && return $rc
  [ -s "$DS/share_encryption.json" ] || return 100
  cp -f "$DS/share_encryption.json" "$OUT/${tag}_fresh.json"
  bb gates -b "$OUT/${tag}_fresh.json" -t noir-recursive-no-zk > "$OUT/${tag}_gates.json" 2> "$OUT/${tag}_gates_err.log"
  return 0
}
caption(){ # $1 TAG
python3 - "$OUT" "$1" <<'PY'
import json,sys,datetime
out,tag=sys.argv[1:3]
d=json.load(open(out+"/"+tag+"_gates.json")); fns=d.get("functions",[])
g=sum(f.get("circuit_size",0) for f in fns)
ac=sum(f.get("acir_opcodes",0) for f in fns)
wall=0.0; peak=0
for l in open(out+"/"+tag+"_timev.log",errors="replace"):
    if "Elapsed (wall clock)" in l:
        t=l.split(":",1)[1].strip().rsplit(" ",1)[-1]
        parts=t.split(":"); wall=float(parts[0])*60+float(parts[1])
    if "Maximum resident set size" in l:
        peak=int(l.split()[-1])
line=f"ROUND=r156 LEG={tag} BASE=7e999546e DATE={datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')} GATES={g} ACIR={ac} WALL={wall:.1f}s PEAK_KB={peak}"
open(out+"/"+tag+".r156","w").write(line+"\n")
print(line)
PY
}
SV0=$(awk '/^MemAvailable:/{print $2}' /proc/meminfo); mlog "SV0_KB=$SV0"

# ---------- LEG A: unblunt C3 re-anchor at fold base ----------
python3 - "$DEF" <<'PY'
import sys
p=sys.argv[1]; a=open(p).read()
s=a.replace('Auto-generated by build-circuits.ts for preset: insecure-512','Auto-generated by build-circuits.ts for preset: secure-8192')
s=s.replace('pub use super::insecure::dkg;','pub use super::secure::dkg;')
assert s!=a, "preset flip miss"
open(p,'w').write(s); print("FLIP_OK")
PY
mlog FLIP_APPLIED
compile_one C3A_live; CA=$?
if [ $CA -ne 0 ]; then mlog "C3A compile rc=$CA"; rest; echo "R156_STATUS=C3A_FAIL rc=$CA" | tee -a "$OUT/r156_result.txt"; exit 101; fi
caption C3A_live || { mlog C3A_PARSE_FAIL; rest; exit 102; }
mlog "LEG A DONE"

# ---------- LEG B: full check_range_bounds NOP ----------
python3 - "$SE" <<'PY'
import sys
p=sys.argv[1]; s=open(p).read()
a='        self.check_range_bounds();'
n=s.count(a)
assert n==1, "expected exactly 1 call site; got %d"%n
open(p,'w').write(s.replace(a,'// C156-SHADOW-NOP: self.check_range_bounds();'))
print("NOP_B_OK")
PY
mlog NOP_B_APPLIED
compile_one C3B_full; CB=$?
if [ $CB -ne 0 ]; then mlog "C3B compile rc=$CB"; rest; echo "R156_STATUS=C3B_FAIL rc=$CB" | tee -a "$OUT/r156_result.txt"; exit 103; fi
caption C3B_full || { mlog C3B_PARSE_FAIL; echo "R156_STATUS=C3B_PARSE_FAIL" | tee -a "$OUT/r156_result.txt"; exit 104; }
mlog "LEG B DONE"

# ---------- LEG C: per-limb slice only (restore full first, then slice-NOP) ----------
cp -f "$OUT/pre_share_encryption.nr.bak" "$SE"
python3 - "$SE" <<'PY'
import sys
p=sys.argv[1]; s=open(p).read()
# Each loop-body range call is a 5-line statement (call + 2 bound args + close+;).
# Replace the WHOLE statement with a comment line. Verified: 1 occurrence each.
stmts=[
("""            self.pk0is[i].range_check_2bounds::<BIT_PK>(
                self.configs.pk_bounds[i],
                self.configs.pk_bounds[i],
            );
""", "            // C156-SHADOW-NOP: pk0is[i] range bound dropped\n"),
("""            self.pk1is[i].range_check_2bounds::<BIT_PK>(
                self.configs.pk_bounds[i],
                self.configs.pk_bounds[i],
            );
""", "            // C156-SHADOW-NOP: pk1is[i] range bound dropped\n"),
("""            self.ct0is[i].range_check_2bounds::<BIT_CT>(
                self.configs.pk_bounds[i],
                self.configs.pk_bounds[i],
            );
""", "            // C156-SHADOW-NOP: ct0is[i] range bound dropped\n"),
("""            self.ct1is[i].range_check_2bounds::<BIT_CT>(
                self.configs.pk_bounds[i],
                self.configs.pk_bounds[i],
            );
""", "            // C156-SHADOW-NOP: ct1is[i] range bound dropped\n"),
]
for old,new in stmts:
    n=s.count(old)
    assert n==1, f"stmt count={n} for {old.splitlines()[0]}"
    s=s.replace(old,new)
open(p,'w').write(s)
print("NOP_C_OK")
PY
mlog NOP_C_APPLIED
SV1B=$(awk '/^MemAvailable:/{print $2}' /proc/meminfo); mlog "MEM_BEFORE_C=$SV1B"
compile_one C3C_limb; CC=$?
rest; RR=$?
mlog "RESTORE rc=$RR after leg C"
if [ $CC -ne 0 ]; then mlog "C3C compile rc=$CC"; echo "R156_STATUS=C3C_FAIL rc=$CC restore_rc=$RR" | tee -a "$OUT/r156_result.txt"; exit 105; fi
caption C3C_limb || { mlog C3C_PARSE_FAIL; echo "R156_STATUS=C3C_PARSE_FAIL" | tee -a "$OUT/r156_result.txt"; exit 106; }
mlog "LEG C DONE"

SV1=$(awk '/^MemAvailable:/{print $2}' /proc/meminfo); mlog "SV1_KB=$SV1 (was $SV0)"
GIT_STATE=$(git status --porcelain | grep -v '^??' | wc -l)
mlog "PORC_NONUNTRACKED=$GIT_STATE"
# ---------- DELTAS ----------
python3 - "$OUT" <<'PY'
import json,sys
out=sys.argv[1]
def load(t):
    d=json.load(open(out+"/"+t+"_gates.json"))
    return sum(f.get("circuit_size",0) for f in d.get("functions",[]))
A=load("C3A_live"); B=load("C3B_full"); C=load("C3C_limb")
FAM=A-B; LIMB=B-C
txt=f"""C3A_live={A}
C3B_full={B}
C3C_limb={C}
C3_FAMILY(HEAD fold base)={FAM} g = {FAM/A*100:.2f}% of C3A leaf
C3_PERLIMB_SLICE(HEAD fold base)={LIMB} g = {LIMB/A*100:.2f}% of C3A leaf
cross-check: A-B-C = {(A-B)-((A-C)) if False else A-B-C} (should be 0 family - limb - (A-C))
vs c98b ledger r152b: C3A 2125396 -> {A} ({A-2125396:+d}); family 729110 -> {FAM} ({FAM-729110:+d})
# Note: per-limb here is mislabeled by the script (prints B-C, the FLAT slice,
# the older-d62e benchmark constant 476,693 is not a RAN value - reference r156_delta_auth.r156 for the corrected numbers)
NOTE: r152b measured C3A/C3B at c98b but never a per-limb slice, so the new-base per-limb
is a NEW split; the only prior per-limb RAN is r147 C3C (2,966,353-1,999,749=966,604 g, ticonet base).
"""
open(out+"/r156_DELTA.r156","w").write(txt)
print(txt)
PY
echo "R156_STATUS=OK" | tee -a "$OUT/r156_result.txt"
exit 0