#!/usr/bin/env bash
# r156 control leg - C3A re-anchor at the R152B ledger type (c98b0d1ca), DEFINA flip visually
# (visually the same as the flour base's legs). Purpose: proves that the DEFINA attention passive path
# of r156ের reproduces r152b's 2,125,396 g, and that the -847 g leaves difference is purely the corpus-type
# (#1996 + I3), not an exit/count error.
set -u
export PATH="$HOME/.local/bin:$HOME/.nargo/bin:/usr/local/bin:$PATH"
R=/tmp/r151b; OUT=/home/dev/interfold-research/interfold/poc/r156
DEF=$R/circuits/lib/src/configs/default/mod.nr
SE=$R/circuits/lib/src/core/dkg/share_encryption.nr
DS=$R/circuits/bin/dkg/target
cp -f "$DEF" "$OUT/c98b_def.nr.bak"; cp -f "$SE" "$OUT/c98b_se.nr.bak"
sha(){ sha256sum "$1" | cut -d' ' -f1; }
PRE_D=$(sha "$DEF"); PRE_S=$(sha "$SE")
echo "LEG=C3A_c98b BASE=$(git -C $R rev-parse --short=7 HEAD) PRE_DEF=$PRE_D PRE_SE=$PRE_S"
python3 - "$DEF" <<'PY'
import sys
p=sys.argv[1]; a=open(p).read()
s=a.replace('Auto-generated by build-circuits.ts for preset: insecure-512','Auto-generated by build-circuits.ts for preset: secure-8192')
s=s.replace('pub use super::insecure::dkg;','pub use super::secure::dkg;')
assert s!=a, "flip miss"
open(p,'w').write(s); print("FLIP_OK")
PY
cd "$R/circuits/bin/dkg" || exit 96
rm -f "$DS/share_encryption.json"
s=$(date +%s)
/usr/bin/time -v nargo compile --force > "$OUT/c98bA_stdout.log" 2> "$OUT/c98bA_timev.log"
rc=$?; e=$(date +%s); WALL=$((e-s))
echo "compile rc=$rc wall=${WALL}s"
if [ $rc -ne 0 ]; then
  cp -f "$OUT/c98b_def.nr.bak" "$DEF"; cp -f "$OUT/c98b_se.nr.bak" "$SE"
  echo "R156_C腿部98b=FAIL rc=$rc"; exit 111
fi
[ -s "$DS/share_encryption.json" ] || { cp -f "$OUT/c98b_def.nr.bak" "$DEF"; echo FAIL_NO_ARTIFACT; exit 112; }
bb gates -b "$DS/share_encryption.json" -t noir-recursive-no-zk > "$OUT/c98bA_gates.json" 2> "$OUT/c98bA_gates_err.log"
python3 - "$OUT" <<'PY'
import json,sys,datetime
out=sys.argv[1]
d=json.load(open(out+"/c98bA_gates.json"))
g=sum(f.get("circuit_size",0) for f in d.get("functions",[]))
ac=sum(f.get("acir_opcodes",0) for f in d.get("functions",[]))
peak=0
for l in open(out+"/c98bA_timev.log",errors="replace"):
    if "Maximum resident set size" in l: peak=int(l.split()[-1])
print(f"ROUND=r156 LEG=C3A_c98b BASE=c98b0d1ca DATE={datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')} GATES={g} ACIR={ac} PEAK_KB={peak}")
open(out+"/c98bA.r156","w").write(f"GPAR={g}\nGACIR={ac}\n")
PY
# restoration
cp -f "$OUT/c98b_def.nr.bak" "$DEF"; cp -f "$OUT/c98b_se.nr.bak" "$SE"
if [ "$(sha "$DEF")" = "$PRE_D" ] && [ "$(sha "$SE")" = "$PRE_S" ]; then
  echo "RESTORE_OK PORC=$(git -C $R status --porcelain | grep -v '^??' | wc -l)"
fi