#!/usr/bin/env bash
# r163 - C2b (dkg/e_sm_share_computation) per-limb/flat slice @ FOLD base a5d563249.
# Closes the LAST unsliced row on the fold-base DKG family table.
# r152d pinned C2b family = 552,965 g (twin of C2a, base-invariant c98b).
# r158 RAN C2a: whole-fn NOP == per-limb-only NOP => flat = 0, family 100% per-limb.
# C2b shares the IDENTICAL check_range_bounds fn (share_computation.nr L258-274,
# read r163: 3-deep for-mod/for-coeff/for-party triple loop, ONE per-limb
# range_check_standard call, nothing outside the loops but a comment + let q_j).
# DRAFT prediction from the r152d twin-mechanic: B == C (flat = 0) -> family 100% per-limb.
# This round tests that prediction with 3 fresh legs on the SAME fn, on the C2b leaf.
#
# 3-leg plan (sequential, in-session / background foreground, taskset -c 0-3):
#   E1 : unblunt C2b at fold base          -> golden 2,586,563 g (r152d via r158E; cross-base delta printed)
#   B  : C2b with whole check_range_bounds fn body NOP'd (family slice)
#   C  : C2b with only the per-limb interior NOP'd (loop headers kept = scaffold)
# DERIVED: family = E1-B; per-limb(spec-A) = E1-C; flat(scaffold) = C-B.
# Verdict key: B == C (digit-exact) => flat = 0 => C2b family 100% per-limb,
# twin row closed, fold-base table COMPLETE to cell level on every row.
set -u
export PATH="$HOME/.local/bin:$HOME/.nargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
R=/tmp/r163
OUT=/home/dev/interfold-research/interfold/poc/r163
mkdir -p "$OUT"
BIN=$R/circuits/bin/dkg
TGT=$BIN/target
[ "$(awk '/^MemAvailable:/{print $2}' /proc/meminfo)" -ge 12000000 ] || { echo [ERR] low-mem; exit 96; }
CIRB=e_sm_share_computation
log(){ echo "[$(date -u +%FT%TZ)] $*" | tee -a "$OUT/log.r163"; }
cd "$R" || { log ERR; exit 98; }
git rev-parse --short=11 HEAD | grep -q '^a5d5632499a' || { log BASE-NOT-LOCKED; exit 97; }
log "HEAD=$(git rev-parse HEAD) CIRB=$CIRB"
DEF=$R/circuits/lib/src/configs/default/mod.nr
SC=$R/circuits/lib/src/core/dkg/share_computation.nr
PRE_DEF=7f07de82407c9601dd737044af69a068238dd9ff175f51c4d64d8e00980aa207
PRE_SC=44eb78d704d0c4d63d0c50373c5be32242b5c1b93c0e93ae52bd60996ca29e48
[ "$(sha256sum "$DEF" | cut -d' ' -f1)" = "$PRE_DEF" ] || { log PRE_DEF_MISMATCH; exit 99; }
[ "$(sha256sum "$SC"  | cut -d' ' -f1)" = "$PRE_SC"  ] || { log PRE_SC_MISMATCH;  exit 99; }
cp -f "$DEF" "$OUT/zz_default_mod.nr.bak"
cp -f "$SC"  "$OUT/zz_share_computation.nr.bak"
restore(){
  cp -f "$OUT/zz_default_mod.nr.bak" "$DEF"
  cp -f "$OUT/zz_share_computation.nr.bak" "$SC"
  if [ "$(sha256sum "$DEF" | cut -d' ' -f1)" = "$PRE_DEF" ] && [ "$(sha256sum "$SC" | cut -d' ' -f1)" = "$PRE_SC" ]; then
    log "RESTORED rc=0"; return 0
  fi
  log "RESTORED rc=1 (sha mismatch!)"; return 1
}
trap 'log INTERRUPT-RESTORE; restore' TERM INT

flip_def(){
  python3 - "$DEF" <<'PY'
import sys
p=sys.argv[1]; a=open(p,encoding='utf-8').read()
s=a.replace('Auto-generated by build-circuits.ts for preset: insecure-512',
            'Auto-generated by build-circuits.ts for preset: secure-8192')
s=s.replace('pub use super::insecure::dkg;','pub use super::secure::dkg;')
s=s.replace('pub use super::insecure::threshold;','pub use super::secure::threshold;')
assert s!=a, "preset flip miss"
open(p,'w').write(s); print("FLIP_OK")
PY
}
compile_one(){
  local tag=$1 pkg=$2
  local art="$TGT/$pkg.json"
  local s e rc
  cd "$R/circuits/bin/dkg/$pkg" || { log "${tag}_CD_FAIL"; return 96; }
  rm -f "$art"
  s=$(date +%s)
  taskset -c 0-3 /usr/bin/time -v nargo compile --force > "$OUT/${tag}_stdout.log" 2> "$OUT/${tag}_timev.log"
  rc=$?
  e=$(date +%s)
  echo "$((e-s))s" > "$OUT/${tag}_wall.raw"
  log "$tag rc=$rc wall=$((e-s))s"
  cd "$R" || return 99
  [ $rc -ne 0 ] && return $rc
  [ -s "$art" ] || return 100
  cp -f "$art" "$OUT/${tag}_fresh.json"
  bb gates -b "$OUT/${tag}_fresh.json" -t noir-recursive-no-zk > "$OUT/${tag}_gates.json" 2> "$OUT/${tag}_gates_err.log"
  return 0
}
caption(){
  local tag=$1
  python3 - "$OUT" "$tag" <<'PY'
import json,sys,datetime
out,tag=sys.argv[1],sys.argv[2]
try:
  d=json.load(open(out+f'/{tag}_gates.json'))
  fns=d.get('functions',[]); g=sum(f.get('circuit_size',0) for f in fns); ac=sum(f.get('acir_opcodes',0) for f in fns)
  wall=0.0; peak=0
  for l in open(out+f'/{tag}_timev.log',errors='replace'):
    if 'Elapsed (wall clock)' in l:
      t=l.split(':',1)[1].strip().rsplit(' ',1)[-1]
      try: p=t.split(':'); wall=float(p[0])*60+float(p[1])
      except Exception: pass
    if 'Maximum resident set size' in l:
      peak=int(l.split()[-1])
  line=f"ROUND=r163 LEG={tag} BASE=a5d5632499a DATE={datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')} GATES={g} ACIR={ac} WALL={wall:.1f}s PEAK_KB={peak}"
except Exception as e:
  line=f"ROUND=r163 LEG={tag} PARSE_ERR={e}"
open(out+f'/{tag}.r163','w').write(line+"\n")
print(line)
PY
}
### ====== LEG E1: unblunt C2b re-anchor @ fold base a5d5632499a (no LOC edit) ======
flip_def || { log FLIP_FAIL_E1; restore; echo "R163_STATUS=E1_FLIPFAIL" | tee -a "$OUT/log.r163"; exit 107; }
compile_one r163E1_c2b_unblunt "$CIRB" || { log E1_FAIL; restore; echo "R163_STATUS=E1_FAIL" | tee -a "$OUT/log.r163"; exit 101; }
caption r163E1_c2b_unblunt || { log E1_PARSE_FAIL; restore; echo "R163_STATUS=E1_PARSE_FAIL" | tee -a "$OUT/log.r163"; exit 102; }
log "LEG_E1_DONE"
### ====== LEG B: whole check_range_bounds fn body NOP (family slice) ======
python3 - "$SC" <<'PY'
import sys
p=sys.argv[1]; a=open(p,encoding='utf-8').read()
i=a.find('pub fn check_range_bounds')
assert i!=-1, 'fn header not found'
op=a.find(') {', i)+3
assert op != i+3, 'no body-open brace'
cl=a.find('\n}\n', op)+1
assert cl>op
body=a[op:cl]
B='\n'.join(('    // B-NOP '+ln if ln.strip() else ln) for ln in body.split('\n'))
s2=a[:op]+B+a[cl:]
assert s2.count('B-NOP')>=1
assert s2.count('{')==a.count('{') and s2.count('}')==a.count('}'), 'brace balance broken'
open(p,'w').write(s2); print('NOP_B_OK whole_check_range_bounds_body')
PY
log "LEG_B_SPLICE_APPLIED"
compile_one r163B_full "$CIRB" || { log B_FAIL; restore; echo "R163_STATUS=B_FAIL" | tee -a "$OUT/log.r163"; exit 103; }
caption r163B_full || { log B_PARSE_FAIL; restore; echo "R163_STATUS=B_PARSE_FAIL" | tee -a "$OUT/log.r163"; exit 104; }
log "LEG_B_DONE"
### ====== LEG C: per-limb interior NOP, loop headers kept (scaffold stays) ======
cp -f "$OUT/zz_share_computation.nr.bak" "$SC"
python3 - "$SC" <<'PY'
import sys
p=sys.argv[1]; a=open(p,encoding='utf-8').read()
i=a.find('pub fn check_range_bounds')
assert i!=-1, 'fn header not found'
op=a.find(') {', i)+3
cl=a.find('\n}\n', op)+1
body=a[op:cl]
keep=0
out=[]
for ln in body.split('\n'):
    t=ln.strip()
    if t.startswith('for ') or t.endswith('}') or t=="" or ln.lstrip().startswith('//'):
        keep+=1
        out.append(ln)
    else:
        out.append('        // r163-NOP-LIMB '+ln if ln.strip() else ln)
new='\n'.join(out)
s2=a[:op]+new+a[cl:]
assert s2.count('r163-NOP-LIMB')>=1
assert s2.count('{')==a.count('{') and s2.count('}')==a.count('}'), 'brace balance broken'
open(p,'w').write(s2); print('NOP_C_OK inner_loop_bodies_commented keep=%d'%keep)
PY
log "LEG_C_SPLICE_APPLIED"
compile_one r163C_limb "$CIRB" || { log C_FAIL; restore; echo "R163_STATUS=C_FAIL" | tee -a "$OUT/log.r163"; exit 105; }
caption r163C_limb || { log C_PARSE_FAIL; restore; echo "R163_STATUS=C_PARSE_FAIL" | tee -a "$OUT/log.r163"; exit 106; }
log "LEG_C_DONE"
restore
R_RESTORE=$?
log "RESTORE rc=$R_RESTORE after leg C"
git -C "$R" status --porcelain | grep -v '^??' | head -5
python3 - "$OUT" <<'PY'
import json,sys
out=sys.argv[1]
def load(t):
  try:
    d=json.load(open(out+f'/{t}_gates.json'))
    return sum(f.get('circuit_size',0) for f in d.get('functions',[]))
  except Exception:
    return None
E1=load('r163E1_c2b_unblunt'); B=load('r163B_full'); C=load('r163C_limb')
lines=['ROUND=r163 BASE=a5d5632499a (fold tip at r162: r161 9d4a86352 + 2 receipt commits)']
lines.append(f'LEG E1 (C2b unblunt)  = {E1}')
lines.append(f'LEG B  (C2b whole-fn-NOP) = {B}')
lines.append(f'LEG C  (C2b per-limb only) = {C}')
if E1 is not None and B is not None and C is not None:
  lines.append(f'C2b FAMILY  = E1-B  = {E1-B} g = {(E1-B)/E1*100:.2f}% of E1 leaf (r152d golden 552,965; delta {(E1-B)-552965})')
  lines.append(f'C2b PER-LIMB (spec-A) = E1-C = {E1-C} g = {(E1-C)/E1*100:.2f}% of leaf; {(E1-C)/(E1-B)*100 if (E1-B) else 0:.2f}% of family')
  lines.append(f'C2b FLAT (scaffold) = C-B = {C-B} g')
  lines.append(f'VERDICT-KEY: B==C? {B==C}  -> flat=0 => family 100% per-limb' if (B==C) else f'VERDICT-KEY: B!=C  -> flat = {C-B} g nonzero')
  lines.append(f'cross-base: E1 fold={E1} vs r152d/r158-fold-golden 2586563 (delta {E1-2586563})')
open(out+'/r163_delta.r163','w').write('\n'.join(lines)+'\n')
print('\n'.join(lines))
PY
echo "R163_STATUS=OK" | tee -a "$OUT/log.r163"
exit 0
