#!/usr/bin/env bash
# r159 - C1 e_sm_lifted solo-NOP @ FOLD tip f7c87dbb9 (post-#1996 + folds).
# 2 legs, measurement only (NEVER shipped); LOCUS + DEF splicing is byte-exact restored.
#   A1 unblunt re-anchor
#   B  e_sm_lifted range check solo NOP (only that call comment-block)
# Worktree: /tmp/r159 @ f7c87dbb9 (detached). Vessel: in-session foreground + /usr/bin/time -v + taskset -c 0-3.
set -u
export PATH="$HOME/.local/bin:$HOME/.nargo/bin:/usr/local/bin:$PATH"
cd /tmp/r159 || { echo "[ERR] cd worktree"; exit 96; }
OUT=/home/dev/interfold-research/interfold/poc/r159
mkdir -p "$OUT"
DEF=/tmp/r159/circuits/lib/src/configs/default/mod.nr
PK=/tmp/r159/circuits/lib/src/core/threshold/pk_generation.nr
TB=/tmp/r159/circuits/bin/threshold
ART=$TB/target/pk_generation.json
PRE_DEF=7f07de82407c9601dd737044af69a068238dd9ff175f51c4d64d8e00980aa207
PRE_PK=8e37436bdca8ff0c58bc4307e2ab9ace2ed40a0d6d5211e244818a23ef50436a
log(){ echo "[$(date -u +%FT%TZ)] $*"; }
echo "=== r159 worktree @ $(git -C /tmp/r159 rev-parse HEAD) ===" | tee -a "$OUT/log.r159"
log "PRE_DEF_SHA=$(sha256sum "$DEF" | cut -d' ' -f1)"
log "PRE_PK_SHA =$(sha256sum "$PK" | cut -d' ' -f1)"
if [ "$(sha256sum "$DEF" | cut -d' ' -f1)" != "$PRE_DEF" ] || [ "$(sha256sum "$PK" | cut -d' ' -f1)" != "$PRE_PK" ]; then
  log "PRE-SHA MISMATCH - aborting"; exit 97
fi
cp -f "$DEF" "$OUT/zz_default_mod.nr.bak"
cp -f "$PK"  "$OUT/zz_pk_generation.nr.bak"
restore(){
cp -f "$OUT/zz_default_mod.nr.bak" "$DEF"
cp -f "$OUT/zz_pk_generation.nr.bak" "$PK"
if [ "$(sha256sum "$DEF" | cut -d' ' -f1)" = "$PRE_DEF" ] && [ "$(sha256sum "$PK" | cut -d' ' -f1)" = "$PRE_PK" ]; then
  log "RESTORED rc=0"; return 0
fi
log "RESTORED rc=1 (sha mismatch!)"; return 1
}
trap 'log INTERRUPT-RESTORE; restore' TERM INT

flip_def(){
python3 - "$DEF" <<'PY'
import sys
p=sys.argv[1]; a=open(p).read()
s=a.replace('Auto-generated by build-circuits.ts for preset: insecure-512','Auto-generated by build-circuits.ts for preset: secure-8192')
s=s.replace('pub use super::insecure::dkg;','pub use super::secure::dkg;')
s=s.replace('pub use super::insecure::threshold;','pub use super::secure::threshold;')
assert s!=a, "preset flip miss"
open(p,'w').write(s); print("FLIP_OK")
PY
}

compile_one(){
  local tag=$1
  cd "$TB" || return 96
  rm -f "$ART"
  local s e
  s=$(date +%s)
  taskset -c 0-3 /usr/bin/time -v nargo compile --force > "$OUT/${tag}_stdout.log" 2> "$OUT/${tag}_timev.log"
  local rc=$?
  e=$(date +%s)
  echo "$((e-s))s" > "$OUT/${tag}_wall.raw"
  log "$tag rc=$rc wall=$((e-s))s"
  cd /tmp/r159 || return 99
  [ $rc -ne 0 ] && return $rc
  [ -s "$ART" ] || return 100
  cp -f "$ART" "$OUT/${tag}_fresh.json"
  bb gates -b "$OUT/${tag}_fresh.json" -t noir-recursive-no-zk > "$OUT/${tag}_gates.json" 2> "$OUT/${tag}_gates_err.log"
  return 0
}

caption(){
python3 - "$OUT" "$1" <<'PY'
import json,sys,datetime
out,tag=sys.argv[1:3]
d=json.load(open(out+"/"+tag+"_gates.json"))
fns=d.get("functions",[]); g=sum(f.get("circuit_size",0) for f in fns); ac=sum(f.get("acir_opcodes",0) for f in fns)
wall=0.0; peak=0
for l in open(out+"/"+tag+"_timev.log",errors="replace"):
    if "Elapsed (wall clock)" in l:
        t=l.split(":",1)[1].strip().rsplit(" ",1)[-1]
        try: p=t.split(":"); wall=float(p[0])*60+float(p[1])
        except Exception: pass
    if "Maximum resident set size" in l:
        peak=int(l.split()[-1])
line="ROUND=r159 LEG=%s BASE=f7c87dbb9 DATE=%s GATES=%d ACIR=%d WALL=%.1fs PEAK_KB=%d"%(
  tag, datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ'), g, ac, wall, peak)
open(out+"/"+tag+".r159","w").write(line+"\n")
print(line)
PY
}

# ============ LEG A1: unblunt re-anchor ============
flip_def || { log FLIP_FAIL; exit 97; }
log FLIPPED
MV0_KB=$(awk '/^MemAvailable:/{print $2}' /proc/meminfo)
log "MEM_AVAIL_KB_BEFORE_A1=$MV0_KB"
compile_one r159A1_live; R_A1=$?
if [ $R_A1 -ne 0 ]; then log "A1 compile rc=$R_A1"; restore; echo "R159_STATUS=A1_FAIL rc=$R_A1" | tee -a "$OUT/log.r159"; exit 101; fi
caption r159A1_live || { log A1_PARSE_FAIL; restore; exit 102; }
log "LEG A1 DONE rc=$R_A1"

# ============ LEG B: e_sm_lifted range_check_2bounds solo NOP ============
python3 - "$PK" <<'PY'
import sys
p=sys.argv[1]; s=open(p).read()
# The call lands on 4 lines + trailing whitespace; matching with a strict multi-line sentinel.
old='''        self.e_sm_lifted.range_check_2bounds::<BIT_E_SM_LIFTED>(
            self.configs.e_sm_bound,
            self.configs.e_sm_bound,
        );
'''
n=s.count(old); assert n==1, "expected exactly 1 e_sm_lifted range-check call-site; got %d" % n
new='''        // R159-SHADOW-NOP-ESM-LIFTED: self.e_sm_lifted.range_check_2bounds::<BIT_E_SM_LIFTED>(
        //     self.configs.e_sm_bound,
        //     self.configs.e_sm_bound,
        // );
'''
s2=s.replace(old,new)
assert s2.count('R159-SHADOW-NOP-ESM-LIFTED')==1
# eek/sk flat checks must still be live
assert s2.count('self.eek.range_check_2bounds')==1
assert s2.count('self.sk.range_check_2bounds')==1
# Loop body all four limb checks must still be live
assert s2.count('self.pk0[i].range_check_2bounds')==1
assert s2.count('self.e_sm[i].range_check_2bounds')==1
assert s2.count('self.e_sm_quotients[i].range_check_2bounds')==1
assert s2.count('self.r[i].range_check_2bounds')==1
assert s2.count('{')==s.count('{') and s2.count('}')==s.count('}'), "brace balance broken"
open(p,'w').write(s2); print("NOP_ESM_LIFTED_OK")
PY
log "LEG B SPLICE APPLIED"
compile_one r159B_esm_lifted_solo; R_B=$?
if [ $R_B -ne 0 ]; then log "B compile rc=$R_B"; restore; echo "R159_STATUS=B_FAIL rc=$R_B" | tee -a "$OUT/log.r159"; exit 103; fi
caption r159B_esm_lifted_solo || { log B_PARSE_FAIL; restore; exit 104; }
log "LEG B DONE rc=$R_B"

MV1_KB=$(awk '/^MemAvailable:/{print $2}' /proc/meminfo)
log "MEM_AVAIL_KB_AFTER=$MV1_KB (was $MV0_KB; net change=$((MV1_KB-MV0_KB)) kB)"
restore; R_RESTORE=$?
log "RESTORE rc=$R_RESTORE after leg B"

# ============ DELTAS (raw RAN only; cross with r157 goldens) ============
python3 - "$OUT" <<'PY'
import json,sys
def load(t):
  d=json.load(open(sys.argv[1]+"/"+t+"_gates.json"))
  return sum(f.get("circuit_size",0) for f in d.get("functions",[]))
A1=load("r159A1_live"); B=load("r159B_esm_lifted_solo")
# r157 goldens on the byte-identical locus (C1 leaf + family cells):
R157_A1=1634722; R157_B=620203; R157_C=823709
fam_r157=R157_A1-R157_B           # 1,014,519
limb_r157=R157_A1-R157_C          # 811,013
flat_r157=R157_C-R157_B           # 203,506
esm_solo=A1-B                      # e_sm_lifted solo gate cost (RAN)
# What are the other 2 flat cells AFTER removing e_sm_lifted?
flat_rem=flat_r157-esm_solo        # eek(5-bit) + sk(1-bit) combined, RAN by subtraction (drug-invariant)
txt=f"""r159 C1 e_sm_lifted solo @ FOLD tip f7c87dbb9, non-locus delta:
  RAN legs:
    A1 unblunt          = {A1} g
    B  e_sm_lifted solo = {B} g
  r157 goldens (byte-identical C1 locus, RAN at c98b-r157 base 247298ad5):
    A1 = {R157_A1} g   (delta vs here {A1-R157_A1:+d})
    B  = {R157_B} g    (full range bullshit: eek+sk+e_sm_lifted+loop; r157 leg)
    C  = {R157_C} g    (per-limb loop only NOP; eek+sk+e_sm_lifted kept)
  base-stability check (A1 digits):  fold f7c87dbb9={A1}  vs c98b-r157=247298ad5:{R157_A1}
                                     delta {A1-R157_A1:+d}
  RAN this round:
    e_sm_lifted solo cost  = {esm_solo} g  ({esm_solo/A1*100:.2f}% of unblunt leaf)
  Carry (RAN at base, by subtraction):
    remaining flat (eek + sk)  = {flat_rem} g  ({flat_rem/A1*100:.2f}% of unblunt leaf)
      identity check: {esm_solo} + {flat_rem} = {esm_solo+flat_rem}; r157-flat = {flat_r157}
      identity delta:   {(esm_solo+flat_rem)-flat_r157:+d}
  Reclassified C1 split (family = per-limb + flat; flat = e_sm_lifted + rem_flat):
    per-limb   = {limb_r157} g  (r157, byte-identical locus)
    e_sm_lifted= {esm_solo} g  (this round, RAN)
    eek + sk   = {flat_rem} g  (this round, RAN by subtraction from r157 flat)
    identity   per-limb + e_sm_lifted + rem_flat = {limb_r157} + {esm_solo} + {flat_rem} = {limb_r157+esm_solo+flat_rem}
             vs r157-family = {fam_r157}: delta {(limb_r157+esm_solo+flat_rem)-fam_r157:+d}
"""
open(sys.argv[1]+"/r159_delta.r159","w").write(txt)
print(txt)
PY

# ============ STALE-ARTIFACT SENTINEL (pre-commit safety) ============
rm -f /tmp/r159/NEVER-SHIP-IF-THIS-ARTIFACT-IS-UNTRACKED
PORC_NONUNTRACKED=$(git -C /tmp/r159 status --porcelain | grep -v '^??' | wc -l)
log "PORC_NONUNTRACKED=$PORC_NONUNTRACKED"
[ "$PORC_NONUNTRACKED" -eq 0 ] || { log "LEG B left modified files"; exit 107; }
echo "R159_STATUS=OK" | tee -a "$OUT/log.r159"
exit 0