#!/usr/bin/env bash
# r161 - C3 flat 3-leg solo, one single invocation per leg:
#   args:  r161_leg_one.sh <u|e0|e1>
# DEF flipped ONCE and stays flipped across all 3 legs (carried between invocations).
# SE restored between legs (each leg starts from unblunt on flipped DEF).
# Vessel: foreground + /usr/bin/time -v + taskset -c 0-3.
set -u
export PATH="$HOME/.local/bin:$HOME/.nargo/bin:/usr/local/bin:$PATH"
[ $# -eq 1 ] || { echo "usage: $0 <u|e0|e1>"; exit 64; }
CELL=$1
case "$CELL" in u|e0|e1) ;; *) echo "bad cell: $CELL"; exit 65; esac
TAG="r161$(tr '[:lower:]' '[:upper:]' <<< "$CELL")"
DSUFFIX=""   # r161U_u / r161E0_e0 / r161E1_e1 form; lowercase the first-letter tag for filename consistency
case "$CELL" in u) DSUFFIX=u ;; e0) DSUFFIX=e0 ;; e1) DSUFFIX=e1 ;; esac
FILE_TAG="r161${TAG}_${DSUFFIX}"   # r161U_u / r161E0_e0 / r161E1_e1
cd /tmp/r161 || exit 96
OUT=/home/dev/interfold-research/interfold/poc/r161
mkdir -p "$OUT"
DEF=/tmp/r161/circuits/lib/src/configs/default/mod.nr
SE=/tmp/r161/circuits/lib/src/core/dkg/share_encryption.nr
DS=/tmp/r161/circuits/bin/dkg
ART=$DS/target/share_encryption.json
PRE_DEF=7f07de82407c9601dd737044af69a068238dd9ff175f51c4d64d8e00980aa207
PRE_SE=308c8c5dd1f7b00a6650bfafd3c5336511964463a64591c7063e5e258f08756e
log(){ echo "[$(date -u +%FT%TZ)] $*"; }
# Preserve DEF.pre-flip backup only if absent
[ -f "$OUT/zz_default_mod.nr.bak" ] || cp -f "$DEF" "$OUT/zz_default_mod.nr.bak"
[ -f "$OUT/zz_share_encryption.nr.bak" ] || cp -f "$SE" "$OUT/zz_share_encryption.nr.bak"
# Sanity: SE must be at PRE_SE on entry (each leg starts unblunt)
if [ "$(sha256sum "$SE" | cut -d' ' -f1)" != "$PRE_SE" ]; then
  log "SE not PRE_SE at entry; restoring"
  cp -f "$OUT/zz_share_encryption.nr.bak" "$SE"
fi
# DEF: if not already flipped (as prior leg left it flipped), flip now; else carry
DEF_SHA_NOW=$(sha256sum "$DEF" | cut -d' ' -f1)
DEF_FLIPPED=0
python3 - "$DEF" <<'PY'
import sys
p=sys.argv[1]; a=open(p).read()
if 'preset: secure-8192' in a and 'pub use super::secure::dkg;' in a:
    print("ALREADY_FLIPPED"); sys.exit(0)
print("NEEDS_FLIP"); sys.exit(1)
PY
FLIP_DETECTOR=$?
if [ $FLIP_DETECTOR -eq 1 ]; then
  python3 - "$DEF" <<'PY'
import sys
p=sys.argv[1]; a=open(p).read()
s=a.replace('Auto-generated by build-circuits.ts for preset: insecure-512','Auto-generated by build-circuits.ts for preset: secure-8192')
s=s.replace('pub use super::insecure::dkg;','pub use super::secure::dkg;')
assert s!=a, "flip miss"
open(p,'w').write(s)
PY
  log "DEF FLIPPED this leg"
  DEF_FLIPPED=1
else
  log "DEF ALREADY FLIPPED from prior leg (carried)"
fi
# Restore SE between legs (each leg starts unblunt)
cp -f "$OUT/zz_share_encryption.nr.bak" "$SE"
restore_SE(){ cp -f "$OUT/zz_share_encryption.nr.bak" "$SE"; }
# Splice: line-comment one cell
python3 - "$SE" "$CELL" <<'PY'
import sys, re
p, cell = sys.argv[1:3]
s = open(p).read()
old = f'        self.{cell}.range_check_2bounds'
assert s.count(old) == 1, f"expected 1 {cell} call; got {s.count(old)}"
line_start = s.rfind('\n', 0, s.index(old)) + 1
line_end   = s.find('\n', s.index(old) + len(old))
line = s[line_start:line_end+1]
new_line = '        // R161-SHADOW-NOP-' + cell.upper() + ': ' + line.strip()
s2 = s[:line_start] + new_line + s[line_end+1:]
assert s2.count('R161-SHADOW-NOP-' + cell.upper()) == 1
other = [x for x in ('u','e0','e1') if x != cell]
assert s2.count('self.message.range_check_standard') == 1
for m in ('pk0is[i]','pk1is[i]','ct0is[i]','ct1is[i]'):
    assert s2.count(f'self.{m}.range_check_2bounds') == 1, f"{m} missing"
for x in other:
    assert s2.count(f'self.{x}.range_check_2bounds') == 1, f"{x} missing"
live = re.findall(rf'^\s+self\.{cell}\.range_check_2bounds', s2, flags=re.M)
assert len(live) == 0, "expected 0 live calls"
assert s2.count('{') == s.count('{') and s2.count('}') == s.count('}'), "brace broken"
open(p,'w').write(s2)
print(f"SPLICE_OK {cell}")
PY
[ $? -ne 0 ] && { log "SPLICE_FAIL $CELL"; restore_SE; exit 97; }
# Flick DEF+SE sha just before compile
log "PRE-COMPILE: DEF=$(sha256sum "$DEF" | cut -c1-8) SE=$(sha256sum "$SE" | cut -c1-8)"
MV0_KB=$(awk '/^MemAvailable:/{print $2}' /proc/meminfo)
log "MEM_AVAIL_KB_BEFORE_$CELL=$MV0_KB"
# Compile
cd "$DS" || exit 96
rm -f "$ART"
S=$(date +%s)
taskset -c 0-3 /usr/bin/time -v nargo compile --force > "$OUT/${FILE_TAG}_stdout.log" 2> "$OUT/${FILE_TAG}_timev.log"
RC=$?
E=$(date +%s)
echo "$((E-S))s" > "$OUT/${FILE_TAG}_wall.raw"
log "COMPILE $FILE_TAG rc=$RC wall=$((E-S))s"
cd /tmp/r161 || exit 99
# Restore SE regardless of RC (next leg starts unblunt)
restore_SE
if [ $RC -ne 0 ]; then
  log "LEG $CELL FAIL rc=$RC"
  echo "R161_STATUS=${CELL}_FAIL rc=$RC" | tee -a "$OUT/log.r161"
  exit 130
fi
[ -s "$ART" ] || { log "ART MISSING"; exit 131; }
cp -f "$ART" "$OUT/${FILE_TAG}_fresh.json"
bb gates -b "$OUT/${FILE_TAG}_fresh.json" -t noir-recursive-no-zk > "$OUT/${FILE_TAG}_gates.json" 2> "$OUT/${FILE_TAG}_gates_err.log"
# Caption
python3 - "$OUT" "$FILE_TAG" "$CELL" <<'PY'
import json, sys, datetime
out, tag, cell = sys.argv[1:4]
d = json.load(open(out + "/" + tag + "_gates.json"))
fns = d.get("functions", [])
g = sum(f.get("circuit_size", 0) for f in fns)
ac = sum(f.get("acir_opcodes", 0) for f in fns)
wall, peak = 0.0, 0
for ln in open(out + "/" + tag + "_timev.log", errors="replace"):
    if "Elapsed (wall clock)" in ln:
        t = ln.split(":", 1)[1].strip().rsplit(" ", 1)[-1]
        try:
            p = t.split(":"); wall = float(p[0])*60 + float(p[1])
        except Exception: pass
    if "Maximum resident set size" in ln:
        peak = int(ln.split()[-1])
line = f"ROUND=r161 LEG={tag} CELL={cell} BASE=733eb45ae DATE={datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')} GATES={g} ACIR={ac} WALL={wall:.1f}s PEAK_KB={peak}"
open(out + "/" + tag + ".r161", "w").write(line + "\n")
print(line)
PY
MV1_KB=$(awk '/^MemAvailable:/{print $2}' /proc/meminfo)
log "MEM_AVAIL_KB_AFTER_$CELL=$MV1_KB"
log "LEG $CELL OK"
exit 0