#!/usr/bin/env bash
# r151b - C3A-only re-anchor on origin tip c98b0d1ca (#1999 new base).
# Single leg, measurement-only, detached worktree, artifact path FIXED
# (prior-tick bug: missing cd back to worktree => target/ next to present
# directory instead of worktree). Golden: r147 C3A 2,966,353 g secure-8192/min.
# Tree restored byte-exact on every exit path; artifact sha + source shas captured.
# NEVER shipped; local measurement only.
set -u
export PATH="/usr/local/bin:$HOME/.local/bin:$HOME/.nargo/bin:$PATH"
R=/tmp/r151b
TAG=C3A
WTBIN=$R/circuits/bin/dkg/share_encryption
OUT=/home/dev/interfold-research/interfold/poc/r151
PREV_GOLDEN=2966353
mlog(){ echo "[$(date -u +%FT%TZ)] $*" >&2 || true; }
[ -e "$R" ] || { echo "ERR no worktree"; exit 95; }
cd "$R" || { echo "ERR cd"; exit 96; }
DEF=$R/circuits/lib/src/configs/default/mod.nr
SE=$R/circuits/lib/src/core/dkg/share_encryption.nr
cp -f "$DEF" "$OUT/pre2_default_mod.nr.bak"
cp -f "$SE"  "$OUT/pre2_share_encryption.nr.bak"
HEAD_SHA=$(git rev-parse HEAD)
PRE_DEF=$(sha256sum "$DEF" | cut -d' ' -f1)
PRE_SE=$(sha256sum "$SE" | cut -d' ' -f1)
mlog "PRE_DEF=$PRE_DEF PRE_SE=$PRE_SE HEAD=$HEAD_SHA"
python3 - "$DEF" <<'PY'
import sys
p=sys.argv[1]; a=open(p).read()
s=a.replace('Auto-generated by build-circuits.ts for preset: insecure-512','Auto-generated by build-circuits.ts for preset: secure-8192')
s=s.replace('pub use super::insecure::dkg;','pub use super::secure::dkg;')
s=s.replace('pub use super::insecure::threshold;','pub use super::secure::threshold;')
assert s!=a, "preset flip string miss"
open(p,'w').write(s)
PY
mlog FLIPPED
cd "$WTBIN" || { mlog CD_FAIL; exit 97; }
rm -f target/share_encryption.json
mlog C3A_COMPILE_START
taskset -c 0-3 /usr/bin/time -v nargo compile --force > "$OUT/C3A2_compile_stdout.log" 2> "$OUT/C3A2_compile_timev.log"
RC=$?
echo "COMPILE_RC=$RC" >> "$OUT/C3A2_compile_timev.log"
cd "$R" || { mlog CD2_FAIL; exit 98; }
cp -f "$OUT/pre2_default_mod.nr.bak" "$DEF"
cp -f "$OUT/pre2_share_encryption.nr.bak" "$SE"
mlog RESTORED diff=$(diff -q "$OUT/pre2_default_mod.nr.bak" "$DEF" >/dev/null && diff -q "$OUT/pre2_share_encryption.nr.bak" "$SE" >/dev/null && echo OK || echo BAD)
if [ "$RC" -ne 0 ]; then mlog "LEG FAILED rc=$RC"; exit "$RC"; fi
[ -s "$WTBIN/target/share_encryption.json" ] || { mlog NO_ARTIFACT; exit 99; }
cp -f "$WTBIN/target/share_encryption.json" "$OUT/C3A2_fresh.json"
FRESH=$(sha256sum "$OUT/C3A2_fresh.json" | cut -d' ' -f1)
bb gates -b "$OUT/C3A2_fresh.json" -t noir-recursive-no-zk > "$OUT/C3A2_gates_raw.json" 2> "$OUT/C3A2_gates_err.log"
python3 - "$OUT" "$TAG" "$FRESH" "$PREV_GOLDEN" "$PRE_DEF" "$PRE_SE" <<'PY'
import json,sys,datetime
out,tag,fresh,prev,predef,pres=(sys.argv[1:7]); prev=float(prev)
d=json.load(open(f"{out}/{tag}_gates_raw.json")); fns=d.get("functions",[])
g=sum(f.get("circuit_size",0) for f in fns); ac=sum(f.get("acir_opcodes",0) for f in fns)
wall=0.0; peak=0
for l in open(f"{out}/{tag}_compile_timev.log",errors="replace"):
    if "Elapsed (wall clock)" in l:
        mm,ss=l.rsplit(":",1); wall=float(mm)*60+float(ss)
    if "Maximum resident set size" in l: peak=int(l.split()[-1])
delta=int(g)-int(prev); pct=delta/prev*100
open(f"{out}/{tag}2.r151","w").write(f"""ROUND=r151b LEG={tag} DATE={datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')}
COMPILE_RC=0
WALL_TIME={int(wall//60)}:{int(wall%60):02d}.{int(wall%1)*10}
PEAK_RSS_KB={peak}
FRESH_SHA256={fresh} PRE_DEF_SHA={predef} PRE_SE_SHA={pres}
GATES={int(g)} PREV_GOLDEN_E3_MIN={int(prev)} DELTA={int(delta)} DELTA_PCT={pct:+.2f}%
ACIR_OPS={int(ac)}
""")
print(f"{tag} GATES={int(g)} ACIR={int(ac)} WALL={wall:.1f}s PEAK_KB={peak} PREV={int(prev)} DELTA={int(delta)} ({pct:+.2f}%) FRESH={fresh[:12]}")
PY