#!/usr/bin/env bash
# r152b - C3A(re-run) + C3B legs on new base c98b0d1ca (#1999), FIXED artifact path.
# nargo under a WTBIN bin drops the artifact at the WORKSPACE target dir the
# workspace member knows about: /tmp/r151b/circuits/bin/dkg/target/share_encryption.json.
# The old r151b/r152 scripts cd'd into circuits/bin/dkg/share_encryption (no own
# Nargo.toml after #1999?) -- actually the leg that SUCCEEDED earlier wrote to
# /tmp/r151b/circuits/bin/dkg/target/share_encryption.json. Capture from THERE.
# Both legs measurement-only. Tree restored byte-exact on every exit.
set -u
export PATH="$HOME/.local/bin:$HOME/.nargo/bin:/usr/local/bin:$PATH"
R=/tmp/r151b
OUT=/home/dev/interfold-research/interfold/poc/r151
WTBIN=$R/circuits/bin/dkg
DS=$R/circuits/bin/dkg/target
DEF=$R/circuits/lib/src/configs/default/mod.nr
SE=$R/circuits/lib/src/core/dkg/share_encryption.nr
GOLDEN_C3A=2125396   # prior r151b run on same base (multi-run RAN)
OLD_C3A=2966353      # r39/r41/r75/r84 + r145/r146/r147 (d62e22e base)
OLD_C3B=1827697      # r146/r147 C3B (d62e22e base)
mlog(){ echo "[$(date -u +%FT%TZ)] $*" >&2; }
cd "$R" || { mlog ERR; exit 96; }
PRE_DEF=$(sha256sum "$DEF" | cut -d' ' -f1)
PRE_SE=$(sha256sum  "$SE"  | cut -d' ' -f1)
if [ "$PRE_DEF" != "7f07de82407c9601dd737044af69a068238dd9ff175f51c4d64d8e00980aa207" ] || \
   [ "$PRE_SE"  != "b7106b5ebae5abe74bc8c4c76b0568b3bf0b877fb3f4eefec5cc9a24dfb1da2c" ]; then
  mlog "PRE-SHA MISMATCH DEF=$PRE_DEF SE=$PRE_SE"; exit 97; fi
if [ -n "$(git status --porcelain)" ]; then mlog "DIRTY TREE"; git status --porcelain | head -5 >&2; exit 98; fi
cp -f "$DEF" "$OUT/pre2_default_mod.nr.bak"
cp -f "$SE"  "$OUT/pre2_share_encryption.nr.bak"
rest(){
  cp -f "$OUT/pre2_default_mod.nr.bak" "$DEF"
  cp -f "$OUT/pre2_share_encryption.nr.bak" "$SE"
  if diff -q "$OUT/pre2_default_mod.nr.bak" "$DEF" >/dev/null && \
     diff -q "$OUT/pre2_share_encryption.nr.bak" "$SE" >/dev/null; then
    mlog "RESTORED rc=0"; return 0
  fi
  mlog "RESTORED rc=1 (sha mismatch!)"; return 1;
}
trap 'mlog INTERRUPT-RESTORE; rest' TERM INT
flip(){
  python3 - "$DEF" <<'PY'
import sys
p=sys.argv[1]; a=open(p).read()
s=a.replace('Auto-generated by build-circuits.ts for preset: insecure-512','Auto-generated by build-circuits.ts for preset: secure-8192')
s=s.replace('pub use super::insecure::dkg;','pub use super::secure::dkg;')
assert s!=a, "preset flip miss"
open(p,'w').write(s)
print("FLIP_OK")
PY
}
compile_one(){ # $1 TAG
  local tag=$1 rc
  if ! grep -q 'secure-8192' "$DEF"; then mlog "$tag NO-FLIP"; return 80; fi
  cd "$WTBIN" || return 96
  rm -f "$DS"/share_encryption.json
  local s e
  s=$(date +%s)
  /usr/bin/time -v nargo compile --force > "$OUT/${tag}_stdout.log" 2> "$OUT/${tag}_timev.log" &
  NC_PID=$!
  ( sleep 2; taskset -c 0-3 -p "$NC_PID" 2>/dev/null; true ) &
  wait "$NC_PID"; rc=$?
  e=$(date +%s)
  echo "$((e-s))" > "$OUT/${tag}_wall.raw"
  mlog "$tag rc=$rc wall=$((e-s))s"
  cd "$R" || return 99
  [ $rc -ne 0 ] && return $rc
  [ -s "$DS/share_encryption.json" ] || return 100
  cp -f "$DS/share_encryption.json" "$OUT/${tag}_fresh.json"
  bb gates -b "$OUT/${tag}_fresh.json" -t noir-recursive-no-zk > "$OUT/${tag}_gates.json" 2> "$OUT/${tag}_gates_err.log"
  return 0
}
pythonz(){ # dump RAN caption from $1 (TAG)
  python3 - "$OUT" "$1" "$GOLDEN_C3A" <<'PY'
import json,sys,datetime
out,tag,golden=sys.argv[1:4]; golden=int(golden)
d=json.load(open(out+"/"+tag+"_gates.json")); fns=d.get("functions",[])
g=sum(f.get("circuit_size",0) for f in fns)
ac=sum(f.get("acir_opcodes",0) for f in fns)
wall=0.0; peak=0
for l in open(out+"/"+tag+"_timev.log",errors="replace"):
    if "Elapsed (wall clock)" in l:
        t=l.split(":",1)[1].strip().rsplit(" ",1)[-1]  # e.g. 1:03.17
        parts=t.split(":"); wall=float(parts[0])*60+float(parts[1])
    if "Maximum resident set size" in l:
        peak=int(l.split()[-1])
diff_=g-golden if tag=="C3A2b" else 0
line=f"ROUND=r152b LEG={tag} BASE=c98b0d1ca DATE={datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')} GATES={g} ACIR={ac} WALL={wall:.1f}s PEAK_KB={peak} DELTA_VS_PRIOR_MULTIRUN={diff_}"
open(out+"/"+tag+".r152b","w").write(line+"\n")
print(line)
PY
}
SV0=$(awk '/^MemAvailable:/{print $2}' /proc/meminfo)
mlog "SV0_KB=$SV0"

# ---------- LEG A: unblunt C3 re-anchor (expect 2,125,396) ----------
flip || { mlog FLIP_FAIL; rest; exit 90; }
compile_one C3A2b; CA=$?
if [ $CA -ne 0 ]; then mlog "C3A compile rc=$CA"; rest; exit 101; fi
AA=$(pythonz C3A2b) || { mlog C3A_PARSE_FAIL; rest; exit 102; }
# sanity gate: our prior r151b multi-run RAN number
GREP_GA=$(sed -n 's/.*GATES=\([0-9]*\).*/\1/p' "$OUT/C3A2b.r152b")
if [ "$GREP_GA" != "$GOLDEN_C3A" ]; then
  mlog "C3A SANITY FAIL: re-anchor got $GREP_GA prior multi-run RAN $GOLDEN_C3A -> NO B-QUOTE"
  rest; echo "R152B_STATUS=C3A_SANITY_FAIL GA=$GREP_GA WANT=$GOLDEN_C3A" | tee -a "$OUT/r152b_result.txt"
  exit 103
fi
mlog "C3A SANITY PASS $GREP_GA"

# ---------- LEG B: full range-NOP ----------
python3 - "$SE" <<'PY'
import sys
p=sys.argv[1]; s=open(p).read()
a='        self.check_range_bounds();'
n=s.count(a)
assert n==1, "expected exactly 1 call site; got %d"%n
open(p,'w').write(s.replace(a,'// C3B-SHADOW-NOP: self.check_range_bounds();'))
print("NOP_OK")
PY
mlog NOP_APPLIED
compile_one C3B2b; CB=$?
rest; RR=$?
mlog "RESTORE rc=$RR"
if [ $CB -ne 0 ] || [ $RR -ne 0 ]; then
  echo "R152B_STATUS=C3B_FAIL compile_rc=$CB restore_rc=$RR" | tee -a "$OUT/r152b_result.txt"
  exit 104
fi
BB=$(pythonz C3B2b) || { mlog C3B_PARSE_FAIL; exit 105; }
SV1=$(awk '/^MemAvailable:/{print $2}' /proc/meminfo)
# Final diff-vs-restash sanity
GIT_STATE=$(git status --porcelain)
# compute family delta
python3 - "$OUT" "$GOLDEN_C3A" "$OLD_C3A" "$OLD_C3B" <<'PY'
import json,sys
out,golden,oldA,oldB=sys.argv[1:5]
golden,oldA,oldB=int(golden),int(oldA),int(oldB)
def load(t):
    d=json.load(open(out+"/"+t+"_gates.json"))
    return sum(f.get("circuit_size",0) for f in d.get("functions",[]))
ga=load("C3A2b"); gb=load("C3B2b")
fam=ga-gb
with open(out+"/r152b_DELTA.r152b","w") as fh:
    fh.write(f"""C3A_newbase={ga} (expect {golden})
C3B_newbase={gb}
NEW_FAMILY={fam} g = {fam/ga*100:.2f}% of new C3A leaf = {fam/11558499*100:.2f}% of old DKG base 11,558,499 g
C3A_newbase_vs_prior_multirun {golden} = {ga-golden} diff
NEW_FAMILY_vs_old_C3B {oldB} = {fam-oldB} ({(fam-oldB)/oldB*100:+.2f}%)
C3A_newbase_vs_old_base {oldA} = {ga-oldA} ({(ga-oldA)/oldA*100:+.2f}%)
SV0_KB=SV0 / SV1_KB=(measured)
""")
print(open(out+"/r152b_DELTA.r152b").read())
PY
echo "GIT_PORT=$(echo "$GIT_STATE" | grep -vc '^$')"
echo "R152B_STATUS=OK" | tee -a "$OUT/r152b_result.txt"
exit 0