#!/usr/bin/env bash
# r152 C3B leg: share_encryption range-full-NOP on the NEW upstream base
# c98b0d1ca (#1999 "bound openings, quotients and VK trees").
# Companion to r151b C3A (unblunt re-anchor on same base = 2,125,396 g, already
# captured on disk in poc/r151/C3A2_fresh.json). This leg gives the new range-NOP
# leg, so we can quote the new family delta = C3A - C3B.
#
# Detached worktree at /tmp/r151b (HEAD c98b0d1ca, source restored byte-exact
# after r151b C3A leg). Source will be byte-restored on EVERY exit path.
# Measurement-only; NEVER run as a shipped/config artifact; telecom-free.
#
# Same systemd unit class as r145/r146/r147/r149 (8c box, taskset 0-3, 31G cap
# via service; local run uses no service wrapper, MemAvailable guard is on-box
# safe at nargo peak <= ~8 GiB).
set -u
export PATH="/usr/local/bin:$HOME/.local/bin:$HOME/.nargo/bin:$PATH"
OUT=/home/dev/interfold-research/interfold/poc/r151
R=/tmp/r151b
WTBIN=$R/circuits/bin/dkg/share_encryption
DEF=$R/circuits/lib/src/configs/default/mod.nr
SE=$R/circuits/lib/src/core/dkg/share_encryption.nr
GOLDEN_OLD_C3B=1827697   # r147/146 C3B on old base (for the vs-old comparison)
GOLDEN_OLD_C3A=2966353   # r146/r147/r145 C3A on old base
mlog(){ echo "[$(date -u +%FT%TZ)] $*" >&2; }

cd "$R" || { echo "ERR cd"; exit 96; }
# Pre-leg sanity: HEAD must be c98b0d1ca; files must be at canonical sha for that base.
HEAD_SHA=$(git rev-parse HEAD)
PRE_DEF=$(sha256sum "$DEF" | cut -d' ' -f1)
PRE_SE=$(sha256sum  "$SE"  | cut -d' ' -f1)
mlog "HEAD=$HEAD_SHA PRE_DEF=$PRE_DEF PRE_SE=$PRE_SE"
if [ "$PRE_DEF" != "7f07de82407c9601dd737044af69a068238dd9ff175f51c4d64d8e00980aa207" ]; then
  mlog "PRE_DEF MISMATCH (expected 7f07de82); abort"; exit 97; fi
if [ "$PRE_SE"  != "b7106b5ebae5abe74bc8c4c76b0568b3bf0b877fb3f4eefec5cc9a24dfb1da2c" ]; then
  mlog "PRE_SE MISMATCH (expected b7106b5e); abort"; exit 98; fi
# Space guard (nargo C3 ~= 8 GiB peak; keep >= 20 GiB available to be safe).
AVAIL_KB=$(awk '/^MemAvailable:/{print $2}' /proc/meminfo)
if [ "$AVAIL_KB" -lt 20000000 ]; then
  mlog "NOGO_PRE_MEM avail_kb=$AVAIL_KB (<20G)"; exit 99; fi
mlog "AVAIL_KB=$AVAIL_KB"

# Backup the two editable files (restore from these on EVERY exit path).
cp -f "$DEF" "$OUT/r152_pre_default_mod.nr.bak"
cp -f "$SE"  "$OUT/r152_pre_share_encryption.nr.bak"
rest(){ cp -f "$OUT/r152_pre_default_mod.nr.bak" "$DEF"; cp -f "$OUT/r152_pre_share_encryption.nr.bak" "$SE";
        diff -q "$OUT/r152_pre_default_mod.nr.bak" "$DEF" >/dev/null && diff -q "$OUT/r152_pre_share_encryption.nr.bak" "$SE" >/dev/null;
        local rc=$?; mlog "RESTORED_SEED rc=$rc"; exit $rc; }
trap 'mlog INTERRUPT-RESTORE; rest' TERM INT

# (1) Flip the preset: insecure-512 -> secure-8192.
python3 - "$DEF" <<'PY'
import sys
p=sys.argv[1]; a=open(p).read()
s=a.replace('Auto-generated by build-circuits.ts for preset: insecure-512','Auto-generated by build-circuits.ts for preset: secure-8192')
s=s.replace('pub use super::insecure::dkg;','pub use super::secure::dkg;')
s=s.replace('pub use super::insecure::threshold;','pub use super::secure::threshold;')
assert s!=a, "no preset flip on new base"
open(p,'w').write(s)
print("FLIP_OK")
PY
mlog FLIPPED
# (2) Full-NOP the single call-site to check_range_bounds() (measurement only).
python3 - "$SE" <<'PY'
import sys
p=sys.argv[1]; s=open(p).read()
a='        self.check_range_bounds();'
n=s.count(a)
assert n==1, "expected exactly 1 call site on new base; got %d" % n
s=s.replace(a, '// C3B-SHADOW-NOP: self.check_range_bounds();')
open(p,'w').write(s)
print("NOP_C3B_OK")
PY
mlog NOPPED

# (3) Compile (same @4c shape as r147/r146/r145/r149).
cd "$WTBIN" || { mlog CDN; rest 96; }
rm -f target/share_encryption.json
start_epoch=$(date +%s)
taskset -c 0-3 /usr/bin/time -v nargo compile --force > "$OUT/r152_C3B_compile_stdout.log" 2> "$OUT/r152_C3B_compile_timev.log"
RC=$?
end_epoch=$(date +%s)
echo "COMPILE_RC=$RC" >> "$OUT/r152_C3B_compile_timev.log"
echo "WALL_SEC=$((end_epoch-start_epoch))" >> "$OUT/r152_C3B_compile_timev.log"
mlog "C3B_COMPILE_RC=$RC WALL=$((end_epoch-start_epoch))s"
cd "$R" || { mlog CD2N; rest 96; }
# (4) Restore source to byte-exact regardless of RC.
rest 0 2>&1 | tee -a "$OUT/r152_run.log" || true
[ "$RC" -ne 0 ] && { mlog "LEG RC=$RC"; exit "$RC"; }
[ -s "$WTBIN/target/share_encryption.json" ] || { mlog "NO_ARTIFACT"; exit 100; }
cp -f "$WTBIN/target/share_encryption.json" "$OUT/r152_C3B_fresh.json"
FRESH=$(sha256sum "$OUT/r152_C3B_fresh.json" | cut -d' ' -f1)
bb gates -b "$OUT/r152_C3B_fresh.json" -t noir-recursive-no-zk > "$OUT/r152_C3B_gates_raw.json" 2> "$OUT/r152_C3B_gates_err.log"
mlog "GATES_RC=$? FRESH=$FRESH"
python3 - "$OUT" "$FRESH" "$PRE_DEF" "$PRE_SE" "$HEAD_SHA" "$GOLDEN_OLD_C3A" "$GOLDEN_OLD_C3B" <<'PY'
import json,sys,datetime
out,fresh,p,ph,base,oldc3a,oldc3b=sys.argv[1:8]; oldc3a=int(oldc3a); oldc3b=int(oldc3b)
d=json.load(open(f"{out}/r152_C3B_gates_raw.json")); fns=d.get("functions",[])
g=sum(f.get("circuit_size",0) for f in fns); ac=sum(f.get("acir_opcodes",0) for f in fns)
wc=0.0;pk=0;sw=0
for l in open(f"{out}/r152_C3B_compile_timev.log",errors="replace"):
    if "Elapsed (wall clock)" in l:
        mm,ss=l.rsplit(":",1); wc=float(mm)*60+float(ss)
    if "Maximum resident set size" in l: pk=int(l.split()[-1])
    if l.startswith("Swaps:"): sw=int(l.rsplit(":",1)[1].strip())
# C3A on same base (r151b) = 2,125,396; loaded from r151b artifact (C3A2_gates_raw.json)
c3a=json.load(open(f"{out}/C3A2_gates_raw.json"))
c3ag=sum(f.get("circuit_size",0) for f in c3a.get("functions",[]))
newfam=c3ag-g; vsoldfam_new_base_delta=newfam-oldc3b; vsoldfam_total_delta=newfam-oldc3a
open(f"{out}/r152_C3B_FAM.r152","w").write(f"""ROUND=r152 LEG=C3B_newbase DATE={datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')}
BASE=c98b0d1ca (#1999) HEAD={ph} PRE_DEF={p} PRE_SE_PH={p}
COMPILE_RC=0 WALL={int(wc//60)}m{int(wc%60):02d}.{int(wc%1)*10}s PEAK_RSS_KB={pk} SWAPS={sw}
FRESH_SHA256={fresh}
C3A_newbase=2125396   # r151b unblunt (this round's companion; RAN, artifact pinned C3A2_fresh.json)
C3B_newbase={g}      # this leg (RAN)
NEW_FAMILY=C3A-C3B={c3ag}-{g}={newfam} g = {newfam/c3ag*100:.2f}% of new C3A leaf
NEW_FAMILY_PERCENT_OLD_DKG_BASE={newfam/11558499*100:.2f}%  # on old 11,558,499 g DKG base
VS_OLD_BASE_FAMILY(old={oldc3b})=delta={newfam-oldc3b} ({(newfam-oldc3b)/oldc3b*100:+.2f}%)
ACIR_OPS={ac}
""")
print(f"C3B r152 gates={g} ACIR={ac} wall={wc:.1f}s new_family={c3ag-g} ({newfam/c3ag*100:.2f}% of new C3A, {newfam/11558499*100:.2f}% of old DKG base)")
PY
mlog "LEG_DONE gates_rc=0(call-ok)"
exit 0