#!/usr/bin/env bash
# r152b C3B-ONLY leg: full-NOP of check_range_bounds call site on new base
# c98b0d1ca (#1999). C3A same-base result already RAN this tick: 2,125,396 g
# (artifact poc/r151/C3A2b_fresh.json sha 5a225a2bbfae44b6, gates json pinned).
# Measurement only. Tree restored byte-exact on every exit.
set -u
export PATH="$HOME/.local/bin:$HOME/.nargo/bin:/usr/local/bin:$PATH"
R=/tmp/r151b
OUT=/home/dev/interfold-research/interfold/poc/r151
WTBIN=$R/circuits/bin/dkg
DS=$R/circuits/bin/dkg/target
DEF=$R/circuits/lib/src/configs/default/mod.nr
SE=$R/circuits/lib/src/core/dkg/share_encryption.nr
mlog(){ echo "[$(date -u +%FT%TZ)] $*" >&2; }
cd "$R" || { mlog ERR; exit 96; }
PRE_DEF=$(sha256sum "$DEF" | cut -d' ' -f1)
PRE_SE=$(sha256sum  "$SE"  | cut -d' ' -f1)
if [ "$PRE_DEF" != "7f07de82407c9601dd737044af69a068238dd9ff175f51c4d64d8e00980aa207" ] || \
   [ "$PRE_SE"  != "b7106b5ebae5abe74bc8c4c76b0568b3bf0b877fb3f4eefec5cc9a24dfb1da2c" ]; then
  mlog "PRE-SHA MISMATCH DEF=$PRE_DEF SE=$PRE_SE"; exit 97; fi
if [ -n "$(git status --porcelain)" ]; then mlog DIRTY; git status --porcelain | head -5 >&2; exit 98; fi
cp -f "$DEF" "$OUT/zz_pre_default_mod.nr"; cp -f "$SE" "$OUT/zz_pre_share_encryption.nr"
trap 'mlog TRAP-RESTORE; cp -f "$OUT/zz_pre_default_mod.nr" "$DEF"; cp -f "$OUT/zz_pre_share_encryption.nr" "$SE"; diff -q "$OUT/zz_pre_default_mod.nr" "$DEF" >/dev/null && diff -q "$OUT/zz_pre_share_encryption.nr" "$SE" >/dev/null && mlog RESTORED_OK || mlog RESTORE_FAIL' TERM INT
python3 - "$DEF" <<'PY'
import sys
p=sys.argv[1]; a=open(p).read()
s=a.replace('Auto-generated by build-circuits.ts for preset: insecure-512','Auto-generated by build-circuits.ts for preset: secure-8192')
s=s.replace('pub use super::insecure::dkg;','pub use super::secure::dkg;')
assert s!=a, "preset flip miss"
open(p,'w').write(s); print("FLIP_OK")
PY
mlog FLIPPED
python3 - "$SE" <<'PY'
import sys
p=sys.argv[1]; s=open(p).read()
a='        self.check_range_bounds();'
n=s.count(a)
assert n==1, "expected exactly 1 call site; got %d" % n
open(p,'w').write(s.replace(a,'// C3B-SHADOW-NOP: self.check_range_bounds();'))
print("NOP_OK")
PY
mlog NOPPED
cd "$WTBIN" || { mlog CDN; exit 96; }
rm -f "$DS/share_encryption.json"
s=$(date +%s)
/usr/bin/time -v nargo compile --force > "$OUT/r152b_C3B_stdout.log" 2> "$OUT/r152b_C3B_timev.log"
RC=$?
e=$(date +%s)
echo "WALL=$((e-s))s"
mlog "C3B rc=$RC wall=$((e-s))s"
cd "$R" || { mlog CDN2; exit 96; }
cp -f "$OUT/zz_pre_default_mod.nr" "$DEF"
cp -f "$OUT/zz_pre_share_encryption.nr" "$SE"
if diff -q "$OUT/zz_pre_default_mod.nr" "$DEF" >/dev/null && diff -q "$OUT/zz_pre_share_encryption.nr" "$SE" >/dev/null; then
  mlog RESTORED_OK
else
  mlog RESTORED_FAIL; exit 103; fi
[ $RC -ne 0 ] && { mlog COMPILE_FAIL; exit $RC; }
[ -s "$DS/share_encryption.json" ] || { mlog NO_ARTIFACT; exit 100; }
cp -f "$DS/share_encryption.json" "$OUT/r152b_C3B_fresh.json"
rm -f "$DS/share_encryption.json"
bb gates -b "$OUT/r152b_C3B_fresh.json" -t noir-recursive-no-zk > "$OUT/r152b_C3B_gates.json" 2> "$OUT/r152b_C3B_gates_err.log"
BR=$?
mlog "GATES_RC=$BR"
FR=$(sha256sum "$OUT/r152b_C3B_fresh.json" | cut -d' ' -f1)
python3 - "$OUT" "$FR" <<'PY'
import json,sys
out,fr=sys.argv[1:3]
d=json.load(open(out+"/r152b_C3B_gates.json")); fns=d.get("functions",[])
g=sum(f.get("circuit_size",0) for f in fns)
ac=sum(f.get("acir_opcodes",0) for f in fns)
wall=0.0; peak=0
for l in open(out+"/r152b_C3B_timev.log",errors="replace"):
    if "Elapsed (wall clock)" in l:
        t=l.split(":",1)[1].strip().split()[-1]; p=t.split(":"); wall=float(p[0])*60+float(p[1])
    if "Maximum resident set size" in l: peak=int(l.split()[-1])
C3A=2125396
fam=C3A-g
open(out+"/r152b_C3B.r152b","w").write(f"ROUND=r152b LEG=C3B BASE=c98b0d1ca GATES={g} ACIR={ac} WALL={wall:.1f}s PEAK_KB={peak} FRESH_{fr}\nNEW_FAMILY=C3A-C3B={fam} g = {fam/C3A*100:.2f}% of C3A new leaf = {fam/11558499*100:.2f}% of old DKG base\n")
print(open(out+"/r152b_C3B.r152b").read())
PY
mlog DONE
exit 0