[workspace]
members = [
    "eval_key_galois_share",
    "eval_key_relin_round1_share",
    "eval_key_relin_round2_share",
    "pk_generation",
    "pk_aggregation",
    "user_data_encryption",
    "user_data_encryption_ct0",
    "user_data_encryption_ct1",
    "share_decryption",
    "decrypted_shares_aggregation",
]
