#!/usr/bin/env bash
# r152c - C1 pk_generation re-anchor + range-ablation on the NEW upstream base
# c98b0d1ca (#1999 "bound openings, quotients and VK trees").
# 3 legs, measurement only (NEVER shipped):
#   A1 unblunt re-anchor (no golden at the new base yet; re-anchors itself)
#   B  PkGeneration::perform_range_checks() call NOP -> whole range family
#   C  per-limb for-loop of perform_range_checks only NOP (flat eek/sk/e_sm_lifted kept)
# Tree restored byte-exact on every exit path. Vessel: systemd user unit (r152b class).
set -u
export PATH="$HOME/.local/bin:$HOME/.nargo/bin:/usr/local/bin:$PATH"
R=/tmp/r151b
OUT=/home/dev/interfold-research/interfold/poc/r152c
pk=$(realpath "$R"/circuits/lib/src/core/threshold/pk_generation.nr)
def=$(realpath "$R"/circuits/lib/src/configs/default/mod.nr)
bsub=$(realpath "$R"/circuits/bin/threshold/pk_generation)
tgt=$bsub/target   # nargo beta-26 writes to the package-ROOT target, not the pkg subdir
# (r152b artifact-path class: artifact lands at circuits/bin/<subdir>/target/<circ>.json)
pkg_root=$(dirname "$bsub")
tgt=${pkg_root}/target
artifact=$tgt/pk_generation.json
log(){ echo "[$(date -u +%FT%TZ)] $*" | tee -a /tmp/r152c.log; }
cd "$R" || { log ERR; exit 96; }
mkdir -p "$OUT"
PRE_DEF=$(sha256sum "$def" | cut -d' ' -f1)
PRE_PK=$(sha256sum  "$pk"  | cut -d' ' -f1)
if [ "$PRE_DEF" != "7f07de82407c9601dd737044af69a068238dd9ff175f51c4d64d8e00980aa207" ] || [ "$PRE_PK" != "8e37436bdca8ff0c58bc4307e2ab9ace2ed40a0d6d5211e244818a23ef50436a" ]; then log "PRE-SHA MISMATCH def=$PRE_DEF pk=$PRE_PK"; exit 97; fi
if [ -n "$(git status --porcelain)" ]; then log DIRTY; git status --porcelain | head -5; exit 98; fi
AVAIL_KB=$(awk '/^MemAvailable:/{print $2}' /proc/meminfo)
if [ "$AVAIL_KB" -lt 12000000 ]; then log "NOGO_PRE_MEM avail=$AVAIL_KB"; exit 96; fi
log "START def=$PRE_DEF pk=$PRE_PK avail_kb=$AVAIL_KB"
cp -f "$def" "$OUT/zz_default_mod.nr"; cp -f "$pk" "$OUT/zz_pk_generation.nr"
restore(){ log TRAP-RESTORE; cp -f "$OUT/zz_default_mod.nr" "$def"; cp -f "$OUT/zz_pk_generation.nr" "$pk"; if diff -q "$OUT/zz_default_mod.nr" "$def" >/dev/null 2>&1 && diff -q "$OUT/zz_pk_generation.nr" "$pk" >/dev/null 2>&1; then log RESTORED_OK; else log RESTORE_FAIL; fi; }
trap restore TERM INT

run_leg(){
  local TAG=$1
  ( while :; do awk '/^MemTotal:/{t=$2} /^MemAvailable:/{a=$2} END{printf "%d\n",(t-a)/1024}' /proc/meminfo; sleep 8; done ) > "$OUT/${TAG}_ram_trace.log" 2>/dev/null &
  local SAMPID=$!
  local RC S E
  S=$(date +%s)
  taskset -c 0-3 /usr/bin/time -p nargo compile --force > "$OUT/c1_${TAG}_stdout.log" 2> "$OUT/c1_${TAG}_timev.log"
  RC=$?
  E=$(date +%s)
  kill $SAMPID 2>/dev/null; wait $SAMPID 2>/dev/null
  log "${TAG} RC=$RC WALL=$((E-S))s"
  if [ $RC -ne 0 ]; then log "${TAG}_COMPILE_FAIL"; return $RC; fi
  if [ ! -s "$tgt/pk_generation.json" ]; then log "${TAG}_NO_ARTIFACT"; return 100; fi
  cp -f "$tgt/pk_generation.json" "$OUT/c1_${TAG}_fresh.json"; rm -f "$tgt/pk_generation.json"
  log "${TAG}_FRESH_SHA=$(sha256sum "$OUT/c1_${TAG}_fresh.json" | cut -d' ' -f1)"
  bb gates -b "$OUT/c1_${TAG}_fresh.json" -t noir-recursive-no-zk > "$OUT/c1_${TAG}_gates.json" 2> "$OUT/c1_${TAG}_gates_err.log"
  python3 - "$OUT" "$TAG" <<'PY'
import json,sys
out,t=sys.argv[1:3]
d=json.load(open(out+f"/c1_{t}_gates.json")); fns=d.get("functions",[])
g=sum(f.get("circuit_size",0) for f in fns); ac=sum(f.get("acir_opcodes",0) for f in fns)
peak=0; wall=0.0
for l in open(out+f"/c1_{t}_timev.log",errors="replace"):
    if "Maximum resident set size" in l: peak=int(l.split()[-1])
open(out+f"/c1_{t}.r152c","w").write(f"ROUND=r152c LEG={t} BASE=c98b0d1ca GATES={g} ACIR={ac} PEAK_KB={peak}\n")
print(open(out+f"/c1_{t}.r152c").read())
PY
  return 0
}
cd "$bsub" || { log CDN; exit 96; }

python3 - "$def" <<'PY'
import sys
p=sys.argv[1]; a=open(p).read()
s=a.replace('Auto-generated by build-circuits.ts for preset: insecure-512','Auto-generated by build-circuits.ts for preset: secure-8192')
s=s.replace('pub use super::insecure::dkg;','pub use super::secure::dkg;')
s=s.replace('pub use super::insecure::threshold;','pub use super::secure::threshold;')
assert s!=a, "preset flip miss"
open(p,'w').write(s); print("FLIP_OK")
PY
log FLIPPED

# LEG A1: unblunt re-anchor (source untouched)
rm -f "$tgt/pk_generation.json" 2>/dev/null
run_leg A1; A1_RC=$?
log "LEG_A1_RC=$A1_RC"

# LEG B: whole perform_range_checks() call NOP; recompile in the same worktree
python3 - "$pk" <<'PY'
import sys
p=sys.argv[1]; s=open(p).read()
a='        self.perform_range_checks();'
n=s.count(a); assert n==1, "expected exactly 1 call site; got %d" % n
open(p,'w').write(s.replace(a,'// C1B-SHADOW-NOP: self.perform_range_checks();'))
print("NOP_B_OK")
PY
rm -f "$tgt/pk_generation.json" 2>/dev/null
run_leg B; B_RC=$?
log "LEG_B_RC=$B_RC"

# Undo the B splice (byte-exact restore of that one call line)
python3 - "$pk" <<'PY'
import sys
p=sys.argv[1]; s=open(p).read()
s=s.replace('// C1B-SHADOW-NOP: self.perform_range_checks();','        self.perform_range_checks();')
assert 'C1B-SHADOW-NOP' not in s
open(p,'w').write(s); print("UNOP_B_OK")
PY

# LEG C: per-limb for-loop only (flat eek/sk/e_sm_lifted checks kept)
python3 - "$pk" <<'PY'
import sys
p=sys.argv[1]; s=open(p).read()
i0=s.find('fn perform_range_checks(self)')
assert i0!=-1, 'range fn header not found'
hd='        for i in 0..L {\n'; i1=s.find(hd, i0)
assert i1!=-1, 'per-limb for-loop header not found'
e=s.find('\n        }\n', i1); assert e!=-1, 'for-loop tail not found'
end=e+len('\n        }\n')
block=s[i1:end]
assert block.count('{')==1 and block.count('}')==1, 'splice unit brace bug: %d/%d' % (block.count('{'), block.count('}'))
lines=block.split('\n')
new='        // C1C-SHADOW-NOP-PER-LIMB-LOOP-BEGIN (r152c)\n'
for ln in lines[:-1]: new += '        // ' + ln + '\n'
s2=s[:i1]+new+s[end:]
assert s2.count('C1C-SHADOW-NOP-PER-LIMB-LOOP-BEGIN')==1
assert s2.count('self.eek.range_check_2bounds')==1
assert s2.count('self.sk.range_check_2bounds')==1
assert s2.count('self.e_sm_lifted.range_check_2bounds')==1
assert s2.count('{')==s.count('{') and s2.count('}')==s.count('}'), 'file brace balance broken'
open(p,'w').write(s2); print("NOP_C_OK")
PY
rm -f "$tgt/pk_generation.json" 2>/dev/null
run_leg C; C_RC=$?
log "LEG_C_RC=$C_RC"

restore
log "DONE A1=$A1_RC B=$B_RC C=$C_RC"
exit 0