#!/usr/bin/env bash
# r152c C1 re-anchor + range-ablation on the NEW upstream base c98b0d1ca (#1999).
# LEG arg: A1 (unblunt re-anchor) | B (full perform_range_checks NOP) | C (per-limb loop NOP)
# Measurement only; NEVER shipped. Tree restored byte-exact on every exit path.
set -u
export PATH="$HOME/.local/bin:$HOME/.nargo/bin:/usr/local/bin:$PATH"
LEG=${1:?LEG required: A1|B|C}
R=/tmp/r151b
OUT=/home/dev/interfold-research/interfold/poc/r152c
BIN=$R/circuits/bin/threshold
CIR="pk_generation"
DEF=$R/circuits/lib/src/configs/default/mod.nr
PK=$R/circuits/lib/src/core/threshold/pk_generation.nr
# pre-state pins (c98b0d1ca worktree, RAN-verified by this round's scout)
PRE_DEF=7f07de82407c9601dd737044af69a068238dd9ff175f51c4d64d8e00980aa207
PRE_PK=8e37436bdca8ff0c58bc4307e2ab9ace2ed40a0d6d5211e244818a23ef50436a
mlog(){ echo "[$(date -u +%FT%TZ)] $*" >&2; }
cd "$R" || { mlog ERR; exit 96; }
mkdir -p "$OUT"
P_DEF=$(sha256sum "$DEF" | cut -d' ' -f1); P_PK=$(sha256sum "$PK" | cut -d' ' -f1)
if [ "$P_DEF" != "$PRE_DEF" ] || [ "$P_PK" != "$PRE_PK" ]; then
  mlog "PRE-SHA MISMATCH DEF=$P_DEF PK=$P_PK"; exit 97; fi
if [ -n "$(git status --porcelain)" ]; then mlog DIRTY; git status --porcelain | head -5 >&2; exit 98; fi
AVAIL_KB=$(awk '/^MemAvailable:/{print $2}' /proc/meminfo)
if [ "$AVAIL_KB" -lt 12000000 ]; then mlog "NOGO_PRE_MEM avail=$AVAIL_KB"; exit 96; fi
cp -f "$DEF" "$OUT/zz_default_mod.nr"; cp -f "$PK" "$OUT/zz_pk_generation.nr"
trap 'mlog TRAP-RESTORE; cp -f "$OUT/zz_default_mod.nr" "$DEF"; cp -f "$OUT/zz_pk_generation.nr" "$PK"; diff -q "$OUT/zz_default_mod.nr" "$DEF" >/dev/null && diff -q "$OUT/zz_pk_generation.nr" "$PK" >/dev/null && mlog RESTORED_OK || mlog RESTORE_FAIL' TERM INT

flip_preset(){
python3 - "$DEF" <<'PY'
import sys
p=sys.argv[1]; a=open(p).read()
s=a.replace('Auto-generated by build-circuits.ts for preset: insecure-512','Auto-generated by build-circuits.ts for preset: secure-8192')
s=s.replace('pub use super::insecure::dkg;','pub use super::secure::dkg;')
s=s.replace('pub use super::insecure::threshold;','pub use super::secure::threshold;')
assert s!=a, "preset flip miss"
open(p,'w').write(s); print("FLIP_OK")
PY
}
flip_preset || { mlog FLIP_FAIL; cp -f "$OUT/zz_default_mod.nr" "$DEF"; cp -f "$OUT/zz_pk_generation.nr" "$PK"; exit 97; }
mlog FLIPPED

case "$LEG" in
B) python3 - "$PK" <<'PY'
import sys
p=sys.argv[1]; s=open(p).read()
a='        self.perform_range_checks();'
n=s.count(a); assert n==1, "expected exactly 1 call site; got %d" % n
open(p,'w').write(s.replace(a,'// C1B-SHADOW-NOP: self.perform_range_checks();'))
print("NOP_B_OK")
PY
  ;;
C) python3 - "$PK" <<'PY'
import sys
p=sys.argv[1]; s=open(p).read()
# per-limb loop of perform_range_checks: locate the range-fn header first, THEN its for-loop
i0=s.find('fn perform_range_checks(self)')
assert i0!=-1, 'range fn header not found'
hd='        for i in 0..L {\n'; i1=s.find(hd, i0)
assert i1!=-1, 'per-limb for-loop header not found'
e=s.find('\n        }\n', i1); assert e!=-1, 'for-loop tail not found'
end=e+len('\n        }\n')
block=s[i1:end]
assert block.count('{')==1 and block.count('}')==1, 'splice unit brace bug: %d/%d' % (block.count('{'), block.count('}'))
lines=block.split('\n')
new='        // C1C-SHADOW-NOP-PER-LIMB-LOOP-BEGIN (r152c)\n'
for ln in lines[:-1]: new += '        // ' + ln + '\n'
s2=s[:i1]+new+s[end:]
assert s2.count('C1C-SHADOW-NOP-PER-LIMB-LOOP-BEGIN')==1
assert s2.count('self.eek.range_check_2bounds')==1
assert s2.count('self.sk.range_check_2bounds')==1
assert s2.count('self.e_sm_lifted.range_check_2bounds')==1
assert s2.count('{')==s.count('{') and s2.count('}')==s.count('}'), 'file brace balance broken'
open(p,'w').write(s2); print("NOP_C_OK")
PY
  ;;
A1) mlog "LEG A1 = unblunt re-anchor (source untouched)"
esac

cd "$BIN/$CIR" || { mlog CDN; exit 96; }
rm -f "$BIN/target/$CIR.json" 2>/dev/null
s=$(date +%s)
/usr/bin/time -v nargo compile --force > "$OUT/c1_${LEG}_stdout.log" 2> "$OUT/c1_${LEG}_timev.log"
RC=$?
e=$(date +%s); WALL=$((e-s))
echo "COMPILE_RC=$RC" >> "$OUT/c1_${LEG}_timev.log"
mlog "COMPILE rc=$RC wall=${WALL}s"
cd "$R" || exit 96
# restore FIRST (capture artifact before restoring configs is safe: artifact is a separate file)
cp -f "$OUT/zz_default_mod.nr" "$DEF"; cp -f "$OUT/zz_pk_generation.nr" "$PK"
diff -q "$OUT/zz_default_mod.nr" "$DEF" >/dev/null && diff -q "$OUT/zz_pk_generation.nr" "$PK" >/dev/null || { mlog RESTORE_FAIL; exit 103; }
mlog RESTORED_OK
[ $RC -ne 0 ] && { mlog COMPILE_FAIL; exit $RC; }
[ -s "$BIN/target/$CIR.json" ] || { mlog NO_ARTIFACT; exit 100; }
cp -f "$BIN/target/$CIR.json" "$OUT/c1_${LEG}_fresh.json"
rm -f "$BIN/target/$CIR.json"
FR=$(sha256sum "$OUT/c1_${LEG}_fresh.json" | cut -d' ' -f1)
mlog "FRESH_SHA=$FR"
bb gates -b "$OUT/c1_${LEG}_fresh.json" -t noir-recursive-no-zk > "$OUT/c1_${LEG}_gates.json" 2> "$OUT/c1_${LEG}_gates_err.log"
GRC=$?
mlog "GATES_RC=$GRC"
python3 - "$OUT" "$LEG" "$FR" "$WALL" <<'PY'
import json,sys
out,leg,fr,wall=sys.argv[1:5]
d=json.load(open(out+f"/c1_{leg}_gates.json")); fns=d.get("functions",[])
g=sum(f.get("circuit_size",0) for f in fns); ac=sum(f.get("acir_opcodes",0) for f in fns)
peak=0
for l in open(out+f"/c1_{leg}_timev.log",errors="replace"):
    if "Maximum resident set size" in l: peak=int(l.split()[-1])
open(out+f"/c1_{leg}.r152c","w").write(f"ROUND=r152c LEG={leg} BASE=c98b0d1ca GATES={g} ACIR={ac} WALL={wall}s PEAK_KB={peak} FRESH_SHA256={fr}\n")
print(open(out+f"/c1_{leg}.r152c").read())
PY
mlog DONE
exit 0