#!/usr/bin/env bash
# r152d C4 solo re-anchor leg on NEW upstream base c98b0d1ca (#1999).
# Completes the r150 C4A RAN-kill re-confirmation at the new base:
# run the unblunt share_decryption re-anchor at c98b0d1ca -> expected 1,746,030 g r150-era
# golden. If the new gate count diverges from 1,746,030 it does NOT mean the range family
# re-appeared (r150 premise kill still stands on source audit at the new base; the range
# function `perform_range_checks` was added by #1999 only to share_encryption.nr per the
# r152b source diff --0 in share_decryption.nr) -- it is expected noise from #1999's
# global circuit reshaping across ALL leaves.
# Single leg: ~2 min wall. Runs AFTER the 4-leg c22b unit releases nargo; sequential two units.
set -u
export PATH="$HOME/.local/bin:$HOME/.nargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
R=/tmp/r151b
OUT=/home/dev/interfold-research/interfold/poc/r152d
BIN=$R/circuits/bin/dkg
TGT=$BIN/target
CIRD=share_decryption
log(){ echo "[$(date -u +%FT%TZ)] $*" | tee -a /tmp/r152d_c4.log; }
cd "$R" || { log ERR; exit 96; }
mkdir -p "$OUT"
git rev-parse HEAD | grep -qE '^c98b0d1ca' || { log BASE-NOT-LOCKED; exit 97; }
[ "$(git status --porcelain | grep -v '^??')" = "" ] || { log DIRTY; exit 98; }
AVAIL_KB=$(awk '/^MemAvailable:/{print $2}' /proc/meminfo)
[ "$AVAIL_KB" -ge 20000000 ] || { log "NOGO_PRE_MEM=$AVAIL_KB"; exit 96; }
DEF=$R/circuits/lib/src/configs/default/mod.nr
P_DEF=$(sha256sum "$DEF" | cut -d' ' -f1)
J_PRE=$(sha256sum "$TGT/$CIRD.json" 2>/dev/null | cut -d' ' -f1 || echo none)
log "HEAD=$(git rev-parse HEAD) PRE_DEF=$P_DEF PRE_JSON=$J_PRE"
cp -f "$DEF" "$OUT/zz_default_mod_nr_c4"
[ "$J_PRE" != "none" ] && cp -f "$TGT/$CIRD.json" "$OUT/pre_target_${CIRD}.json"
restore(){
  log TRAP-RESTORE
  cp -f "$OUT/zz_default_mod_nr_c4" "$DEF"
  [ "$J_PRE" != "none" ] && cp -f "$OUT/pre_target_${CIRD}.json" "$TGT/$CIRD.json" || rm -f "$TGT/$CIRD.json"
  diff -q "$OUT/zz_default_mod_nr_c4" "$DEF" >/dev/null 2>&1 && log RESTORED_OK || log RESTORE_FAIL
}
trap restore TERM INT
python3 - "$DEF" <<'PY'
import sys
p=sys.argv[1]; a=open(p).read()
s=a.replace('Auto-generated by build-circuits.ts for preset: insecure-512','Auto-generated by build-circuits.ts for preset: secure-8192')
s=s.replace('pub use super::insecure::dkg;','pub use super::secure::dkg;')
s=s.replace('pub use super::insecure::threshold;','pub use super::secure::threshold;')
assert s!=a, 'preset flip miss'
open(p,'w').write(s); print('FLIP_OK')
PY
cd "$BIN/$CIRD" || { log CDN; exit 97; }
rm -f "$TGT/$CIRD.json"
( while :; do awk '/^MemTotal:/{t=$2} /^MemAvailable:/{a=$2} END{printf "%d\n",(t-a)/1024}' /proc/meminfo; sleep 8; done ) > "$OUT/C4_ram_trace.log" 2>/dev/null &
SAMPID=$!
S=$(date +%s)
taskset -c 0-3 /usr/bin/time -p nargo compile --force > "$OUT/C4_stdout.log" 2> "$OUT/C4_timev.log"
RC=$?
E=$(date +%s)
kill "$SAMPID" 2>/dev/null; wait "$SAMPID" 2>/dev/null
log "C4 RC=$RC WALL=$((E-S))s"
cd "$R" || exit 96
# CRITICAL ORDERING: capture the fresh artifact BEFORE restore() replaces the worktree
# copy with the pre-original. (If we captured after restore, gates would measure the
# pre-original, not the r152d fresh compile.)
[ -s "$TGT/$CIRD.json" ] || { log C4_NO_ARTIFACT; restore; exit 100; }
cp -f "$TGT/$CIRD.json" "$OUT/C4_fresh.json"
FR=$(sha256sum "$OUT/C4_fresh.json" | cut -d' ' -f1)
restore
[ $RC -ne 0 ] && { log C4_COMPILE_FAIL RC=$RC; exit $RC; }
bb gates -b "$OUT/C4_fresh.json" -t noir-recursive-no-zk > "$OUT/C4_gates.json" 2> "$OUT/C4_gates_err.log"
python3 - "$OUT" "$FR" <<'PY'
import json,sys
out,fr=sys.argv[1:3]
d=json.load(open(out+'/C4_gates.json')); fns=d.get('functions',[])
g=sum(f.get('circuit_size',0) for f in fns); ac=sum(f.get('acir_opcodes',0) for f in fns)
peak=0; wall=0.0
for l in open(out+'/C4_timev.log', errors='replace'):
    if 'Maximum resident set size' in l: peak=int(l.split()[-1])
    if 'Elapsed (wall clock)' in l: wall=float(l.split()[-1])
open(out+'/C4.r152d','w').write(f'ROUND=r152d LEG=C4 BASE=c98b0d1ca GATES={g} ACIR={ac} WALL={wall:.2f}s PEAK_KB={peak} FRESH_SHA256={fr}\n')
print(open(out+'/C4.r152d').read())
PY
log C4_DONE
exit 0