#!/usr/bin/env bash
# r158 - C2a (dkg/sk_..._share_computation) per-limb/flat split @ FOLD base HEAD 3291d85bd.
# Closes the last unsliced row (C2a family 552,965 g / C2b twin 552,965 g per r152d) and
# provides the 2nd twin's spill (C2b unblunt RAN at fold base, lower-cost sanity leg E).
#
# SOURCE READ FACT (the discriminator premise, verified by this round's RAN -- do NOT take on faith):
#   check_range_bounds (share_computation.nr L258..271) is a 3-deep for-mod_idx/for-coeff/
#   for-party triple loop of per-sub-element range_check_standard calls. There is no non-per-limb
#   ("flat") statement anywhere in the fn body. Therefore:
#     - "whole-fn NOP" (leg B) = whole family
#     - "per-limb for-mod block only NOP" (leg C) = the same span, because the span IS the whole
#       fn interior.
#     - FLAT = B - C = 0 expected.  (Contrast: C1 flat = 203,506 g / 20.06% of family; C3 flat =
#       172,052 g / 23.60% of family.)
#
# 4-leg plan (3 on C2a, 1 on C2b complementary sanity, sequential, in-session foreground):
#   A : unblunt C2a at fold base (no LOC edit, preset flip only)
#       -> expected 1,464,743 g (r152d c98b golden; r157 blob-identity claim says c98b==fold 
#          for the C2a row)
#   B : C2a with whole check_range_bounds fn body NOP'd (family slice)
#       -> expected family = A - B = 552,965 g (r152d base-invariant family)
#   C : C2a with only the while-per-mod_idx block NOP'd (per-limb / spec-A surface)
#       -> expected C = B numerically (flat = 0 discriminator), so per-limb = B - A = 552,965 g
#   E : unblunt C2b at fold base (complementary sanity leg, no LOC edit)
#       -> expected 2,586,563 g (r152d c98b golden, r157 blob claim byte-identical)
#
# Vessel: in-session foreground + taskset -c 0-3 (r156/r157 proved in-session legs work on this
# box; r152d's peaks were ~4-6 GiB on C2a, should be lower post-#/1996 small-N work).
# Artifact path: circuits/bin/dkg/target/<sk-...>.json for C2a; .../e_sm_share_computation.json
# for C2b (workspace-root target, per r152d memory of nargo beta-26 pkg-root layout landing
# here). Memory ceiling note: box is 8c / 31 GiB / 0 swap; previous round peaks were 14-20 GiB
# on C1/C3 class, this leaf is smaller (r152d C2a peak ~4.8 GiB).
set -u
export PATH="$HOME/.local/bin:$HOME/.nargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
R=/tmp/r158
OUT=/home/dev/interfold-research/interfold/poc/r158
mkdir -p "$OUT"
BIN=$R/circuits/bin/dkg
TGT=$BIN/target

# Plenty of headroom check
[ "$(awk '/^MemAvailable:/{print $2}' /proc/meminfo)" -ge 12000000 ] || { echo [ERR] low-mem; exit 96; }

# Set-diff to pick the sk_*_share_computation package name (20-char, transport-safe)
CIRA=$(python3 - "$BIN" <<'PY'
import os,sys
d=sys.argv[1]
cands=[x for x in os.listdir(d) if os.path.isdir(os.path.join(d,x))]
known={'pk','share_encryption','share_decryption','e_sm_share_computation','target'}
diff=[x for x in cands if x not in known]
assert len(diff)==1, diff
print(diff[0])
PY
) || { echo "CIRA_PICKFAIL"; exit 97; }
CIRB=e_sm_share_computation

log(){ echo "[$(date -u +%FT%TZ)] $*" | tee -a "$OUT/log.r158"; }
cd "$R" || { log ERR; exit 98; }
git rev-parse HEAD | grep -q '^3291d85bd' || { log "BASE-NOT-LOCKED"; exit 97; }
log "HEAD=$(git rev-parse HEAD) CIRA=$CIRA CIRB=$CIRB"

DEF=$R/circuits/lib/src/configs/default/mod.nr
SC=$R/circuits/lib/src/core/dkg/share_computation.nr
PRE_DEF=7f07de82407c9601dd737044af69a068238dd9ff175f51c4d64d8e00980aa207
PRE_SC=44eb78d704d0c4d63d0c50373c5be32242b5c1b93c0e93ae52bd60996ca29e48
[ "$(sha256sum "$DEF" | cut -d' ' -f1)" = "$PRE_DEF" ] || { log "PRE_DEF_MISMATCH"; exit 99; }
[ "$(sha256sum "$SC"  | cut -d' ' -f1)" = "$PRE_SC"  ] || { log "PRE_SC_MISMATCH"; exit 99; }
log "DEF_SHA=$(sha256sum "$DEF" | cut -d' ' -f1)"
log "SC_SHA=$(sha256sum "$SC" | cut -d' ' -f1)"

cp -f "$DEF" "$OUT/zz_default_mod.nr.bak"
cp -f "$SC"  "$OUT/zz_share_computation.nr.bak"
restore(){
  cp -f "$OUT/zz_default_mod.nr.bak" "$DEF"
  cp -f "$OUT/zz_share_computation.nr.bak" "$SC"
  if [ "$(sha256sum "$DEF" | cut -d' ' -f1)" = "$PRE_DEF" ] && [ "$(sha256sum "$SC" | cut -d' ' -f1)" = "$PRE_SC" ]; then
    log "RESTORED rc=0"; return 0
  fi
  log "RESTORED rc=1 (sha mismatch!)"; return 1
}
trap 'log INTERRUPT-RESTORE; restore' TERM INT

flip_def(){
  python3 - "$DEF" <<'PY'
import sys
p=sys.argv[1]; a=open(p,encoding='utf-8').read()
s=a.replace('Auto-generated by build-circuits.ts for preset: insecure-512',
            'Auto-generated by build-circuits.ts for preset: secure-8192')
s=s.replace('pub use super::insecure::dkg;','pub use super::secure::dkg;')
s=s.replace('pub use super::insecure::threshold;','pub use super::secure::threshold;')
assert s!=a, "preset flip miss"
open(p,'w').write(s); print("FLIP_OK")
PY
}

compile_one(){
  local tag=$1 pkg=$2
  local art="$TGT/$pkg.json"
  local s e rc
  cd "$R/circuits/bin/dkg/$pkg" || { log "${tag}_CD_FAIL"; return 96; }
  rm -f "$art"
  s=$(date +%s)
  taskset -c 0-3 /usr/bin/time -v nargo compile --force > "$OUT/${tag}_stdout.log" 2> "$OUT/${tag}_timev.log"
  rc=$?
  e=$(date +%s)
  echo "$((e-s))s" > "$OUT/${tag}_wall.raw"
  log "$tag rc=$rc wall=$((e-s))s"
  cd "$R" || return 99
  [ $rc -ne 0 ] && return $rc
  [ -s "$art" ] || return 100
  cp -f "$art" "$OUT/${tag}_fresh.json"
  bb gates -b "$OUT/${tag}_fresh.json" -t noir-recursive-no-zk > "$OUT/${tag}_gates.json" 2> "$OUT/${tag}_gates_err.log"
  return 0
}

caption(){
  local tag=$1
  python3 - "$OUT" "$tag" <<'PY'
import json,sys,datetime
out,tag=sys.argv[1],sys.argv[2]
try:
  d=json.load(open(out+f'/{tag}_gates.json'))
  fns=d.get('functions',[]); g=sum(f.get('circuit_size',0) for f in fns); ac=sum(f.get('acir_opcodes',0) for f in fns)
  wall=0.0; peak=0
  for l in open(out+f'/{tag}_timev.log',errors='replace'):
    if 'Elapsed (wall clock)' in l:
      t=l.split(':',1)[1].strip().rsplit(' ',1)[-1]
      try: p=t.split(':'); wall=float(p[0])*60+float(p[1])
      except Exception: pass
    if 'Maximum resident set size' in l:
      peak=int(l.split()[-1])
  line=f"ROUND=r158 LEG={tag} BASE=3291d85bd DATE={datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')} GATES={g} ACIR={ac} WALL={wall:.1f}s PEAK_KB={peak}"
except Exception as e:
  line=f"ROUND=r158 LEG={tag} PARSE_ERR={e}"
open(out+f'/{tag}.r158','w').write(line+"\n")
print(line)
PY
}

### ====== LEG A: unblunt C2a re-anchor @ fold base ====================
SKIP_A=0
if [ -s "$OUT/r158A_live.r158" ] && grep -q "GATES=1464743" "$OUT/r158A_live.r158"; then
  log "LEG_A_PRESENCING (digit-exact r152d already landed): reusing $(cat "$OUT/r158A_live.r158")"
  SKIP_A=1
fi
if [ "$SKIP_A" -eq 0 ]; then
  flip_def || { log FLIP_FAIL_A; restore; exit 97; }
  compile_one r158A_live "$CIRA" || { log A_FAIL; restore; echo "R158_STATUS=A_FAIL" | tee -a "$OUT/log.r158"; exit 101; }
  caption r158A_live || { log A_PARSE_FAIL; restore; echo "R158_STATUS=A_PARSE_FAIL" | tee -a "$OUT/log.r158"; exit 102; }
else
  # A skipped: DEF still at insecure-512 base. Flip ONCE here so B and C compile under
  # secure-8192 (matching r157: a single flip persists across B/C, which only touch SC).
  flip_def || { log FLIP_FAIL_A_SKIP; restore; exit 97; }
fi
log "LEG_A_DONE"

### ====== LEG B: whole check_range_bounds fn body NOP (family) ====================
# DEF already secure-8192 from the leg-A-skip flip above.
# Splice: line-comment the ENTIRE fn body (from after the opening '{' of the body to just
# before the fn's closing '}'). Token-derived from the pinned file (no typed Noir literals).
python3 - "$SC" <<'PY'
import sys
p=sys.argv[1]; a=open(p,encoding='utf-8').read()
i=a.find('pub fn check_range_bounds')
assert i!=-1, 'fn header not found'
op=a.find(') {', i)+3           # position just AFTER the body-opening '{'
assert op != i+3, 'no body-open brace'
cl=a.find('\n}\n', op)+1        # the fn closing '}'
assert cl>op
body=a[op:cl]
B='\n'.join(('    // B-NOP '+ln if ln.strip() else ln) for ln in body.split('\n'))
s2=a[:op]+B+a[cl:]
assert s2.count('B-NOP')>=1
assert s2.count('{')==a.count('{') and s2.count('}')==a.count('}'), 'brace balance broken'
open(p,'w').write(s2); print('NOP_B_OK whole_check_range_bounds_body')
PY
log "LEG_B_SPLICE_APPLIED"
compile_one r158B_full "$CIRA" || { log B_FAIL; restore; echo "R158_STATUS=B_FAIL" | tee -a "$OUT/log.r158"; exit 103; }
caption r158B_full || { log B_PARSE_FAIL; restore; echo "R158_STATUS=B_PARSE_FAIL" | tee -a "$OUT/log.r158"; exit 104; }
log "LEG_B_DONE"

### ====== LEG C: per-limb inner-loop bodies NOP (scaffold kept; spec-A surface) ==========
cp -f "$OUT/zz_share_computation.nr.bak" "$SC"
# DEF is still secure-8192 from leg-A/B (B does not restore DEF; it only writes SC which C
# then restores itself).
# Splice: line-comment every code-line of check_range_bounds EXCEPT the 3 for-loop headers
# + the 3 closing '}' + blank/comment lines. What stays (costed at leg C = the scaffold):
# the mod_idx/coeff_idx/party_idx loop headers + closers. What is removed: `let q_j` and the
# Polynomial::new(..).range_check_standard(q_j) call (the load-bearing range op).
# per-limb(spec-A)=A-C removed; flat(scaffold)=C-B.
python3 - "$SC" <<'PY'
import sys
p=sys.argv[1]; a=open(p,encoding='utf-8').read()
i=a.find('pub fn check_range_bounds')
assert i!=-1, 'fn header not found'
op=a.find(') {', i)+3
cl=a.find('\n}\n', op)+1
body=a[op:cl]
keep=0
out=[]
for ln in body.split('\n'):
    t=ln.strip()
    if t.startswith('for ') or t.endswith('}') or t=="" or ln.lstrip().startswith('//'):
        keep+=1
        out.append(ln)
    else:
        out.append('        // r158-NOP-LIMB '+ln if ln.strip() else ln)
new='\n'.join(out)
s2=a[:op]+new+a[cl:]
assert s2.count('r158-NOP-LIMB')>=1
assert s2.count('{')==a.count('{') and s2.count('}')==a.count('}'), 'brace balance broken'
open(p,'w').write(s2); print('NOP_C_OK inner_loop_bodies_commented keep=%d'%keep)
PY
log "LEG_C_SPLICE_APPLIED"
compile_one r158C_limb "$CIRA" || { log C_FAIL; restore; echo "R158_STATUS=C_FAIL" | tee -a "$OUT/log.r158"; exit 105; }
caption r158C_limb || { log C_PARSE_FAIL; restore; echo "R158_STATUS=C_PARSE_FAIL" | tee -a "$OUT/log.r158"; exit 106; }
log "LEG_C_DONE"

restore
R_RESTORE=$?
log "RESTORE rc=$R_RESTORE after leg C"

### ====== LEG E: unblunt C2b sanity leg (no LOC edit, additive sanity) ====================
SKIP_E=0
if [ -s "$OUT/r158E_c2b_unblunt.r158" ] && grep -q "GATES=2586563" "$OUT/r158E_c2b_unblunt.r158"; then
  log "LEG_E_PRESENCING (digit-exact r152d already landed): reusing $(cat "$OUT/r158E_c2b_unblunt.r158")"
  SKIP_E=1
fi
if [ "$SKIP_E" -eq 0 ]; then
flip_def || { log FLIP_FAIL_E; restore; echo "R158_STATUS=E_FLIPFAIL" | tee -a "$OUT/log.r158"; exit 107; }
compile_one r158E_c2b_unblunt "$CIRB" || { log E_FAIL; restore; echo "R158_STATUS=E_FAIL" | tee -a "$OUT/log.r158"; }
caption r158E_c2b_unblunt || log E_PARSE_FAIL
fi
log "LEG_E_DONE"

restore
log "PORC_NONTRACKER_NON=[]"
git -C "$R" status --porcelain | grep -v '^\?\?' | head -5

python3 - "$OUT" <<'PY'
import json,sys
out=sys.argv[1]
def load(t):
  try:
    d=json.load(open(out+f'/{t}_gates.json'))
    return sum(f.get('circuit_size',0) for f in d.get('functions',[]))
  except Exception as e:
    return None
A=load('r158A_live'); B=load('r158B_full'); C=load('r158C_limb'); E=load('r158E_c2b_unblunt')
lines=[]
lines.append(f'ROUND=r158\nLEG A (C2a unblunt): A={A}\nLEG B (C2a whole-fn-NOP): B={B}\nLEG C (C2a per-limb only): C={C}\nLEG E (C2b unblunt sanity): E={E}')
if A and B is not None and C is not None and B>=0 and C>=0:
  lines.append(f'\nC2a FAMILY = A-B = {A-B} g = {(A-B)/A*100 if A else 0:.2f}% of A leaf')
  lines.append(f'C2a PER-LIMB (spec-A) = A-C = {A-C} g = {(A-C)/A*100 if A else 0:.2f}% of A leaf; {(A-C)/(A-B)*100 if (A-B) else 0:.2f}% of family')
  lines.append(f'C2a FLAT (outside for-mod) = C-B = {C-B if C is not None else "?"} g')
  if A and B and C and (A-B)==(A-C):  # main discriminator capture
    lines.append(f'\nVERDICT-KEY: (A-C)==(A-B) i.e. flat=0, C2a family is 100% per-limb (spec-A-able)')
lines.append('\nCROSS-BASE (vs r152d c98b):')
lines.append(f'  A C2a: fold-base={A} vs r152d=1464743 (delta {A-1464743 if A else "?"})')
lines.append(f'  B family: A-B={A-B if A and B is not None else "?"} r152d-golden=552965 ')
lines.append(f'  C2b sanity: fold-base={E} vs r152d=2586563 (delta {E-2586563 if E else "?"})')
open(out+'/r158_delta.r158','w').write('\n'.join(lines)+'\n')
print('\n'.join(lines))
PY

echo "R158_STATUS=OK" | tee -a "$OUT/log.r158"
exit 0