#!/usr/bin/env bash
# r157 - C1 pk_generation re-anchor @ FOLD base HEAD 247298ad5 (post-#1996 + fold 6294250f6->f2df52907).
# 3 legs, measurement only (NEVER shipped); LOCS ns splicing is byte-exact-restored:
#   A1 unblunt re-anchor
#   B  perform_range_checks() call full NOP
#   C  per-limb for-loop only NOP (flat eek/sk/e_sm_lifted kept)
# Worktree: /tmp/r157 @ 247298ad5 (detached). Vessel: in-session foreground + /usr/bin/time -v + taskset -c 0-3.
set -u
export PATH="$HOME/.local/bin:$HOME/.nargo/bin:/usr/local/bin:$PATH"
cd /tmp/r157 || { echo "[ERR] cd"; exit 96; }
OUT=/home/dev/interfold-research/interfold/poc/r157
mkdir -p "$OUT"
DEF=/tmp/r157/circuits/lib/src/configs/default/mod.nr
PK=/tmp/r157/circuits/lib/src/core/threshold/pk_generation.nr
TB=/tmp/r157/circuits/bin/threshold
ART=$TB/target/pk_generation.json
PRE_DEF=7f07de82407c9601dd737044af69a068238dd9ff175f51c4d64d8e00980aa207
PRE_PK=8e37436bdca8ff0c58bc4307e2ab9ace2ed40a0d6d5211e244818a23ef50436a
log(){ echo "[$(date -u +%FT%TZ)] $*"; }
mkdir -p "$OUT"
echo "=== r157 worktree @ $(git -C /tmp/r157 rev-parse HEAD) ===" | tee -a "$OUT/log.r157"
log "PRE_DEF_SHA=$(sha256sum "$DEF" | cut -d' ' -f1)"
log "PRE_PK_SHA =$(sha256sum "$PK" | cut -d' ' -f1)"
if [ "$(sha256sum "$DEF" | cut -d' ' -f1)" != "$PRE_DEF" ] || [ "$(sha256sum "$PK" | cut -d' ' -f1)" != "$PRE_PK" ]; then
  log "PRE-SHA MISMATCH - aborting"; exit 97
fi
cp -f "$DEF" "$OUT/zz_default_mod.nr.bak"
cp -f "$PK"  "$OUT/zz_pk_generation.nr.bak"
restore(){
cp -f "$OUT/zz_default_mod.nr.bak" "$DEF"
cp -f "$OUT/zz_pk_generation.nr.bak" "$PK"
if [ "$(sha256sum "$DEF" | cut -d' ' -f1)" = "$PRE_DEF" ] && [ "$(sha256sum "$PK" | cut -d' ' -f1)" = "$PRE_PK" ]; then
  log "RESTORED rc=0"; return 0
fi
log "RESTORED rc=1 (sha mismatch!)"; return 1
}
trap 'log INTERRUPT-RESTORE; restore' TERM INT

flip_def(){
python3 - "$DEF" <<'PY'
import sys
p=sys.argv[1]; a=open(p).read()
s=a.replace('Auto-generated by build-circuits.ts for preset: insecure-512','Auto-generated by build-circuits.ts for preset: secure-8192')
s=s.replace('pub use super::insecure::dkg;','pub use super::secure::dkg;')
s=s.replace('pub use super::insecure::threshold;','pub use super::secure::threshold;')
assert s!=a, "preset flip miss"
open(p,'w').write(s); print("FLIP_OK")
PY
}

compile_one(){ # $1 TAG ; artifact at $ART; bb-gates into ${TAG}_gates.json
  local tag=$1
  cd "$TB" || return 96
  rm -f "$ART"
  local s e
  s=$(date +%s)
  taskset -c 0-3 /usr/bin/time -v nargo compile --force > "$OUT/${tag}_stdout.log" 2> "$OUT/${tag}_timev.log"
  local rc=$?
  e=$(date +%s)
  echo "$((e-s))s" > "$OUT/${tag}_wall.raw"
  log "$tag rc=$rc wall=$((e-s))s"
  cd /tmp/r157 || return 99
  [ $rc -ne 0 ] && return $rc
  [ -s "$ART" ] || return 100
  cp -f "$ART" "$OUT/${tag}_fresh.json"
  bb gates -b "$OUT/${tag}_fresh.json" -t noir-recursive-no-zk > "$OUT/${tag}_gates.json" 2> "$OUT/${tag}_gates_err.log"
  return 0
}

caption(){ # $1 TAG
python3 - "$OUT" "$1" <<'PY'
import json,sys,datetime
out,tag=sys.argv[1:3]
d=json.load(open(out+"/"+tag+"_gates.json"))
fns=d.get("functions",[]); g=sum(f.get("circuit_size",0) for f in fns); ac=sum(f.get("acir_opcodes",0) for f in fns)
wall=0.0; peak=0
for l in open(out+"/"+tag+"_timev.log",errors="replace"):
    if "Elapsed (wall clock)" in l:
        t=l.split(":",1)[1].strip().rsplit(" ",1)[-1]
        try: p=t.split(":"); wall=float(p[0])*60+float(p[1])
        except Exception: pass
    if "Maximum resident set size" in l:
        peak=int(l.split()[-1])
line="ROUND=r157 LEG=%s BASE=247298ad5 DATE=%s GATES=%d ACIR=%d WALL=%.1fs PEAK_KB=%d"%(
  tag, datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ'), g, ac, wall, peak)
open(out+"/"+tag+".r157","w").write(line+"\n")
print(line)
PY
}

# ============ LEG A1: unblunt re-anchor ============
flip_def || { log FLIP_FAIL; exit 97; }
log FLIPPED
MV0_KB=$(awk '/^MemAvailable:/{print $2}' /proc/meminfo)
log "MEM_AVAIL_KB_BEFORE_A1=$MV0_KB"
compile_one r157A1_live; R_A1=$?
if [ $R_A1 -ne 0 ]; then log "A1 compile rc=$R_A1"; restore; echo "R157_STATUS=A1_FAIL rc=$R_A1" | tee -a "$OUT/log.r157"; exit 101; fi
caption r157A1_live || { log A1_PARSE_FAIL; restore; exit 102; }
log "LEG A1 DONE rc=$R_A1"

# ============ LEG B: full perform_range_checks() NOP ============
python3 - "$PK" <<'PY'
import sys
p=sys.argv[1]; s=open(p).read()
a='        self.perform_range_checks();'
n=s.count(a); assert n==1, "expected exactly 1 call site; got %d" % n
open(p,'w').write(s.replace(a,'// C157-SHADOW-NOP-B: self.perform_range_checks();'))
print("NOP_B_OK")
PY
log "LEG B SPLICE APPLIED"
compile_one r157B_full; R_B=$?
if [ $R_B -ne 0 ]; then log "B compile rc=$R_B"; restore; echo "R157_STATUS=B_FAIL rc=$R_B" | tee -a "$OUT/log.r157"; exit 103; fi
caption r157B_full || { log B_PARSE_FAIL; restore; exit 104; }
log "LEG B DONE rc=$R_B"

# ============ LEG C: per-limb for-loop only NOP (restore B first) ============
cp -f "$OUT/zz_pk_generation.nr.bak" "$PK"
python3 - "$PK" <<'PY'
import sys
p=sys.argv[1]; s=open(p).read()
i0=s.find('fn perform_range_checks(self)')
assert i0!=-1, 'range fn header not found'
hd='        for i in 0..L {'; i1=s.find(hd, i0)
assert i1!=-1, 'per-limb for-loop header not found'
e=s.find('\n        }\n', i1); assert e!=-1, 'for-loop tail not found'
end=e+len('\n        }\n')  # r157 fix: e+11 == tail length (first pass e+9 was 2 bytes short -> C==A1, caught in the delta output)
block=s[i1:end]
assert block.count('{')==1 and block.count('}')==1, 'splice unit brace bug: %d/%d' % (block.count('{'), block.count('}'))
lines=block.split('\n')
new='        // C157-SHADOW-NOP-PER-LIMB-LOOP\n'
for ln in lines[:-1]: new += '        // ' + ln + '\n'
s2=s[:i1]+new+s[end:]
assert s2.count('C157-SHADOW-NOP-PER-LIMB-LOOP')==1
assert s2.count('self.eek.range_check_2bounds')==1
assert s2.count('self.sk.range_check_2bounds')==1
assert s2.count('self.e_sm_lifted.range_check_2bounds')==1
assert s2.count('{')==s.count('{') and s2.count('}')==s.count('}'), 'brace balance broken'
open(p,'w').write(s2); print("NOP_C_OK")
PY
log "LEG C SPLICE APPLIED"
compile_one r157C_limb; R_C=$?
log "MEM_BEFORE_RESTORE_KB=$(awk '/^MemAvailable:/{print $2}' /proc/meminfo)"
restore; R_RESTORE=$?
log "RESTORE rc=$R_RESTORE after leg C"
if [ $R_C -ne 0 ]; then log "C compile rc=$R_C"; echo "R157_STATUS=C_FAIL rc=$R_C restore_rc=$R_RESTORE" | tee -a "$OUT/log.r157"; exit 105; fi
caption r157C_limb || { log C_PARSE_FAIL; echo "R157_STATUS=C_PARSE_FAIL" | tee -a "$OUT/log.r157"; exit 106; }
log "LEG C DONE rc=$R_C"

MV1_KB=$(awk '/^MemAvailable:/{print $2}' /proc/meminfo)
log "MEM_AVAIL_KB_AFTER=$MV1_KB (was $MV0_KB before A1; net change=$((MV1_KB-MV0_KB)) kB)"
log "PORC_NONUNTRACKED=$(git -C /tmp/r157 status --porcelain | grep -v '^??' | wc -l)"
# ============ DELTAS (raw RAN only) ============
python3 - "$OUT" <<'PY'
import json,sys,collections
def load(t):
  d=json.load(open(sys.argv[1]+"/"+t+"_gates.json"))
  return sum(f.get("circuit_size",0) for f in d.get("functions",[]))
A=load("r157A1_live"); B=load("r157B_full"); C=load("r157C_limb")
FAM=A-B; LIMB=A-C; FLAT=C-B
assert LIMB+FLAT==FAM, "identity: per-limb+flat != family"
txt=f"""ROUND=r157 C1 fold-base RAN legs:
  A1(unblunt)={A}
  B (range full NOP)={B}
  C (per-limb loop only NOP)={C}
  FAMILY(A1-B)={FAM} g = {FAM/A*100:.2f}% of A1 leaf
  PER-LIMB(A1-C)={LIMB} g = {LIMB/A*100:.2f}% of A1 leaf; {LIMB/FAM*100:.2f}% of family
  FLAT(C-B)={FLAT} g = {FLAT/A*100:.2f}% of A1 leaf; {FLAT/FAM*100:.2f}% of family
  identity: {LIMB}+{FLAT}={LIMB+FLAT}={FAM} (holds)
vs c98b r152c:
  A1={A} c98b=1634682 (delta {A-1634682:+d})
  B ={B} c98b=620203 (delta {B-620203:+d})
  C ={C} c98b=823669 (delta {C-823669:+d})
  FAMILY c98b=1014479 -> fold={FAM} (delta {FAM-1014479:+d})
  PER-LIMB c98b=811013 -> fold={LIMB} (delta {LIMB-811013:+d})
  FLAT c98b=203466  -> fold={FLAT} (delta {FLAT-203466:+d})
"""
open(sys.argv[1]+"/r157_delta.r157","w").write(txt)
print(txt)
PY
echo "R157_STATUS=OK" | tee -a "$OUT/log.r157"
exit 0